// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AvatarMetadataProcessingStatus.
const (
	AvatarMetadataProcessingStatusCompleted  AvatarMetadataProcessingStatus = "completed"
	AvatarMetadataProcessingStatusFailed     AvatarMetadataProcessingStatus = "failed"
	AvatarMetadataProcessingStatusPending    AvatarMetadataProcessingStatus = "pending"
	AvatarMetadataProcessingStatusProcessing AvatarMetadataProcessingStatus = "processing"
)

// Valid indicates whether the value is a known member of the AvatarMetadataProcessingStatus enum.
func (e AvatarMetadataProcessingStatus) Valid() bool {
	switch e {
	case AvatarMetadataProcessingStatusCompleted:
		return true
	case AvatarMetadataProcessingStatusFailed:
		return true
	case AvatarMetadataProcessingStatusPending:
		return true
	case AvatarMetadataProcessingStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for AvatarMetadataUploadStatus.
const (
	AvatarMetadataUploadStatusFailed    AvatarMetadataUploadStatus = "failed"
	AvatarMetadataUploadStatusUploaded  AvatarMetadataUploadStatus = "uploaded"
	AvatarMetadataUploadStatusUploading AvatarMetadataUploadStatus = "uploading"
)

// Valid indicates whether the value is a known member of the AvatarMetadataUploadStatus enum.
func (e AvatarMetadataUploadStatus) Valid() bool {
	switch e {
	case AvatarMetadataUploadStatusFailed:
		return true
	case AvatarMetadataUploadStatusUploaded:
		return true
	case AvatarMetadataUploadStatusUploading:
		return true
	default:
		return false
	}
}

// Defines values for AvatarUploadResponseStatus.
const (
	AvatarUploadResponseStatusCompleted  AvatarUploadResponseStatus = "completed"
	AvatarUploadResponseStatusFailed     AvatarUploadResponseStatus = "failed"
	AvatarUploadResponseStatusProcessing AvatarUploadResponseStatus = "processing"
)

// Valid indicates whether the value is a known member of the AvatarUploadResponseStatus enum.
func (e AvatarUploadResponseStatus) Valid() bool {
	switch e {
	case AvatarUploadResponseStatusCompleted:
		return true
	case AvatarUploadResponseStatusFailed:
		return true
	case AvatarUploadResponseStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for ComponentStatusStatus.
const (
	ComponentStatusStatusError ComponentStatusStatus = "error"
	ComponentStatusStatusOk    ComponentStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the ComponentStatusStatus enum.
func (e ComponentStatusStatus) Valid() bool {
	switch e {
	case ComponentStatusStatusError:
		return true
	case ComponentStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusDegraded HealthStatusStatus = "degraded"
	HealthStatusStatusDown     HealthStatusStatus = "down"
	HealthStatusStatusOk       HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusDegraded:
		return true
	case HealthStatusStatusDown:
		return true
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for LivenessStatusStatus.
const (
	LivenessStatusStatusDown LivenessStatusStatus = "down"
	LivenessStatusStatusOk   LivenessStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the LivenessStatusStatus enum.
func (e LivenessStatusStatus) Valid() bool {
	switch e {
	case LivenessStatusStatusDown:
		return true
	case LivenessStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for GetAvatarByIdParamsSize.
const (
	GetAvatarByIdParamsSizeN100x100 GetAvatarByIdParamsSize = "100x100"
	GetAvatarByIdParamsSizeN300x300 GetAvatarByIdParamsSize = "300x300"
	GetAvatarByIdParamsSizeOriginal GetAvatarByIdParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetAvatarByIdParamsSize enum.
func (e GetAvatarByIdParamsSize) Valid() bool {
	switch e {
	case GetAvatarByIdParamsSizeN100x100:
		return true
	case GetAvatarByIdParamsSizeN300x300:
		return true
	case GetAvatarByIdParamsSizeOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetAvatarByIdParamsFormat.
const (
	GetAvatarByIdParamsFormatJpeg GetAvatarByIdParamsFormat = "jpeg"
	GetAvatarByIdParamsFormatPng  GetAvatarByIdParamsFormat = "png"
	GetAvatarByIdParamsFormatWebp GetAvatarByIdParamsFormat = "webp"
)

// Valid indicates whether the value is a known member of the GetAvatarByIdParamsFormat enum.
func (e GetAvatarByIdParamsFormat) Valid() bool {
	switch e {
	case GetAvatarByIdParamsFormatJpeg:
		return true
	case GetAvatarByIdParamsFormatPng:
		return true
	case GetAvatarByIdParamsFormatWebp:
		return true
	default:
		return false
	}
}

// Defines values for GetUserAvatarParamsSize.
const (
	GetUserAvatarParamsSizeN100x100 GetUserAvatarParamsSize = "100x100"
	GetUserAvatarParamsSizeN300x300 GetUserAvatarParamsSize = "300x300"
	GetUserAvatarParamsSizeOriginal GetUserAvatarParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetUserAvatarParamsSize enum.
func (e GetUserAvatarParamsSize) Valid() bool {
	switch e {
	case GetUserAvatarParamsSizeN100x100:
		return true
	case GetUserAvatarParamsSizeN300x300:
		return true
	case GetUserAvatarParamsSizeOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetUserAvatarParamsFormat.
const (
	GetUserAvatarParamsFormatJpeg GetUserAvatarParamsFormat = "jpeg"
	GetUserAvatarParamsFormatPng  GetUserAvatarParamsFormat = "png"
	GetUserAvatarParamsFormatWebp GetUserAvatarParamsFormat = "webp"
)

// Valid indicates whether the value is a known member of the GetUserAvatarParamsFormat enum.
func (e GetUserAvatarParamsFormat) Valid() bool {
	switch e {
	case GetUserAvatarParamsFormatJpeg:
		return true
	case GetUserAvatarParamsFormatPng:
		return true
	case GetUserAvatarParamsFormatWebp:
		return true
	default:
		return false
	}
}

// AvatarMetadata defines model for AvatarMetadata.
type AvatarMetadata struct {
	CreatedAt  time.Time   `json:"created_at"`
	Dimensions *Dimensions `json:"dimensions,omitempty"`

	// FileName Example: avatar.jpg
	FileName string             `json:"file_name"`
	Id       openapi_types.UUID `json:"id"`

	// MimeType Example: image/jpeg
	MimeType         string                          `json:"mime_type"`
	ProcessingStatus *AvatarMetadataProcessingStatus `json:"processing_status,omitempty"`

	// Size Example: 1024000
	Size         int64                       `json:"size"`
	Thumbnails   *[]ThumbnailInfo            `json:"thumbnails,omitempty"`
	UpdatedAt    time.Time                   `json:"updated_at"`
	UploadStatus *AvatarMetadataUploadStatus `json:"upload_status,omitempty"`
	UserId       string                      `json:"user_id"`
}

// AvatarMetadataProcessingStatus defines model for AvatarMetadata.ProcessingStatus.
type AvatarMetadataProcessingStatus string

// AvatarMetadataUploadStatus defines model for AvatarMetadata.UploadStatus.
type AvatarMetadataUploadStatus string

// AvatarUploadResponse defines model for AvatarUploadResponse.
type AvatarUploadResponse struct {
	CreatedAt time.Time                  `json:"created_at"`
	Id        openapi_types.UUID         `json:"id"`
	Status    AvatarUploadResponseStatus `json:"status"`
	Url       string                     `json:"url"`
	UserId    string                     `json:"user_id"`
}

// AvatarUploadResponseStatus defines model for AvatarUploadResponse.Status.
type AvatarUploadResponseStatus string

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus struct {
	Error     *string               `json:"error,omitempty"`
	LatencyMs *int                  `json:"latency_ms,omitempty"`
	Status    ComponentStatusStatus `json:"status"`
}

// ComponentStatusStatus defines model for ComponentStatus.Status.
type ComponentStatusStatus string

// Dimensions defines model for Dimensions.
type Dimensions struct {
	Height int `json:"height"`
	Width  int `json:"width"`
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// FileTooLargeError defines model for FileTooLargeError.
type FileTooLargeError struct {
	// Error Example: File too large
	Error string `json:"error"`

	// MaxSize Example: 10485760
	MaxSize int64 `json:"max_size"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Components struct {
		Broker   *ComponentStatus `json:"broker,omitempty"`
		Database *ComponentStatus `json:"database,omitempty"`
		S3       *ComponentStatus `json:"s3,omitempty"`
	} `json:"components"`
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// LivenessStatus defines model for LivenessStatus.
type LivenessStatus struct {
	Reason *string              `json:"reason,omitempty"`
	Status LivenessStatusStatus `json:"status"`
}

// LivenessStatusStatus defines model for LivenessStatus.Status.
type LivenessStatusStatus string

// ThumbnailInfo defines model for ThumbnailInfo.
type ThumbnailInfo struct {
	// Size Example: 100x100
	Size string `json:"size"`
	Url  string `json:"url"`
}

// AvatarIdPath defines model for AvatarIdPath.
type AvatarIdPath = openapi_types.UUID

// UserIdHeader defines model for UserIdHeader.
type UserIdHeader = string

// UserIdPath defines model for UserIdPath.
type UserIdPath = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UploadAvatarMultipartBody defines parameters for UploadAvatar.
type UploadAvatarMultipartBody struct {
	// File Файл изображения (JPEG, PNG, WebP), максимум 10MB
	File openapi_types.File `json:"file"`
}

// UploadAvatarParams defines parameters for UploadAvatar.
type UploadAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию
	XUserID UserIdHeader `json:"X-User-ID"`
}

// DeleteAvatarByIdParams defines parameters for DeleteAvatarById.
type DeleteAvatarByIdParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию
	XUserID UserIdHeader `json:"X-User-ID"`
}

// GetAvatarByIdParams defines parameters for GetAvatarById.
type GetAvatarByIdParams struct {
	// Size Требуемый размер изображения
	Size *GetAvatarByIdParamsSize `form:"size,omitempty" json:"size,omitempty"`

	// Format Требуемый формат изображения
	Format *GetAvatarByIdParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetAvatarByIdParamsSize defines parameters for GetAvatarById.
type GetAvatarByIdParamsSize string

// GetAvatarByIdParamsFormat defines parameters for GetAvatarById.
type GetAvatarByIdParamsFormat string

// DeleteUserAvatarParams defines parameters for DeleteUserAvatar.
type DeleteUserAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию
	XUserID UserIdHeader `json:"X-User-ID"`
}

// GetUserAvatarParams defines parameters for GetUserAvatar.
type GetUserAvatarParams struct {
	Size   *GetUserAvatarParamsSize   `form:"size,omitempty" json:"size,omitempty"`
	Format *GetUserAvatarParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetUserAvatarParamsSize defines parameters for GetUserAvatar.
type GetUserAvatarParamsSize string

// GetUserAvatarParamsFormat defines parameters for GetUserAvatar.
type GetUserAvatarParamsFormat string

// ListUserAvatarsParams defines parameters for ListUserAvatars.
type ListUserAvatarsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostUploadFormMultipartBody defines parameters for PostUploadForm.
type PostUploadFormMultipartBody struct {
	File   openapi_types.File `json:"file"`
	UserId *string            `json:"user_id,omitempty"`
}

// UploadAvatarMultipartRequestBody defines body for UploadAvatar for multipart/form-data ContentType.
type UploadAvatarMultipartRequestBody UploadAvatarMultipartBody

// PostUploadFormMultipartRequestBody defines body for PostUploadForm for multipart/form-data ContentType.
type PostUploadFormMultipartRequestBody PostUploadFormMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// UploadAvatar Загрузка аватарки
	// (POST /api/v1/avatars)
	UploadAvatar(ctx echo.Context, params UploadAvatarParams) error
	// DeleteAvatarById Удаление аватарки
	// (DELETE /api/v1/avatars/{avatar_id})
	DeleteAvatarById(ctx echo.Context, avatarId AvatarIdPath, params DeleteAvatarByIdParams) error
	// GetAvatarById Получение аватарки (бинарные данные изображения)
	// (GET /api/v1/avatars/{avatar_id})
	GetAvatarById(ctx echo.Context, avatarId AvatarIdPath, params GetAvatarByIdParams) error
	// GetAvatarMetadata Получение метаданных аватарки
	// (GET /api/v1/avatars/{avatar_id}/metadata)
	GetAvatarMetadata(ctx echo.Context, avatarId AvatarIdPath) error
	// DeleteUserAvatar Удаление текущей аватарки пользователя
	// (DELETE /api/v1/users/{user_id}/avatar)
	DeleteUserAvatar(ctx echo.Context, userId UserIdPath, params DeleteUserAvatarParams) error
	// GetUserAvatar Получение текущей аватарки пользователя
	// (GET /api/v1/users/{user_id}/avatar)
	GetUserAvatar(ctx echo.Context, userId UserIdPath, params GetUserAvatarParams) error
	// ListUserAvatars Список аватарок пользователя
	// (GET /api/v1/users/{user_id}/avatars)
	ListUserAvatars(ctx echo.Context, userId UserIdPath, params ListUserAvatarsParams) error
	// HealthCheck Проверка работоспособности сервиса
	// (GET /health)
	HealthCheck(ctx echo.Context) error
	// LivenessCheck Проба жизнеспособности (liveness)
	// (GET /livez)
	LivenessCheck(ctx echo.Context) error
	// GetGalleryPage Галерея аватарок пользователя
	// (GET /web/gallery/{user_id})
	GetGalleryPage(ctx echo.Context, userId UserIdPath) error
	// GetUploadPage Страница с формой загрузки аватарки
	// (GET /web/upload)
	GetUploadPage(ctx echo.Context) error
	// PostUploadForm Обработка загрузки через веб-форму
	// (POST /web/upload)
	PostUploadForm(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// UploadAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) UploadAvatar(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadAvatarParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UploadAvatar(ctx, params)
	return err
}

// DeleteAvatarById converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAvatarById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAvatarByIdParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAvatarById(ctx, avatarId, params)
	return err
}

// GetAvatarById converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvatarById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAvatarByIdParams
	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", ctx.QueryParams(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter size: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvatarById(ctx, avatarId, params)
	return err
}

// GetAvatarMetadata converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvatarMetadata(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvatarMetadata(ctx, avatarId)
	return err
}

// DeleteUserAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserAvatar(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteUserAvatarParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserAvatar(ctx, userId, params)
	return err
}

// GetUserAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserAvatar(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserAvatarParams
	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", ctx.QueryParams(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter size: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserAvatar(ctx, userId, params)
	return err
}

// ListUserAvatars converts echo context to params.
func (w *ServerInterfaceWrapper) ListUserAvatars(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserAvatarsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUserAvatars(ctx, userId, params)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// LivenessCheck converts echo context to params.
func (w *ServerInterfaceWrapper) LivenessCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LivenessCheck(ctx)
	return err
}

// GetGalleryPage converts echo context to params.
func (w *ServerInterfaceWrapper) GetGalleryPage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGalleryPage(ctx, userId)
	return err
}

// GetUploadPage converts echo context to params.
func (w *ServerInterfaceWrapper) GetUploadPage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUploadPage(ctx)
	return err
}

// PostUploadForm converts echo context to params.
func (w *ServerInterfaceWrapper) PostUploadForm(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUploadForm(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/api/v1/avatars", wrapper.UploadAvatar, options.OperationMiddlewares["uploadAvatar"]...)
	router.DELETE(options.BaseURL+"/api/v1/avatars/:avatar_id", wrapper.DeleteAvatarById, options.OperationMiddlewares["deleteAvatarById"]...)
	router.GET(options.BaseURL+"/api/v1/avatars/:avatar_id", wrapper.GetAvatarById, options.OperationMiddlewares["getAvatarById"]...)
	router.GET(options.BaseURL+"/api/v1/avatars/:avatar_id/metadata", wrapper.GetAvatarMetadata, options.OperationMiddlewares["getAvatarMetadata"]...)
	router.DELETE(options.BaseURL+"/api/v1/users/:user_id/avatar", wrapper.DeleteUserAvatar, options.OperationMiddlewares["deleteUserAvatar"]...)
	router.GET(options.BaseURL+"/api/v1/users/:user_id/avatar", wrapper.GetUserAvatar, options.OperationMiddlewares["getUserAvatar"]...)
	router.GET(options.BaseURL+"/api/v1/users/:user_id/avatars", wrapper.ListUserAvatars, options.OperationMiddlewares["listUserAvatars"]...)
	router.GET(options.BaseURL+"/health", wrapper.HealthCheck, options.OperationMiddlewares["healthCheck"]...)
	router.GET(options.BaseURL+"/livez", wrapper.LivenessCheck, options.OperationMiddlewares["livenessCheck"]...)
	router.GET(options.BaseURL+"/web/upload", wrapper.GetUploadPage, options.OperationMiddlewares["getUploadPage"]...)
	router.POST(options.BaseURL+"/web/upload", wrapper.PostUploadForm, options.OperationMiddlewares["postUploadForm"]...)
	router.GET(options.BaseURL+"/web/gallery/:user_id", wrapper.GetGalleryPage, options.OperationMiddlewares["getGalleryPage"]...)

}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type ServiceUnavailableJSONResponse Error

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsJSONResponse struct {
	Body Error

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedJSONResponse Error

type UploadAvatarRequestObject struct {
	Params UploadAvatarParams
	Body   *multipart.Reader
}

type UploadAvatarResponseObject interface {
	VisitUploadAvatarResponse(w http.ResponseWriter) error
}

type UploadAvatar201JSONResponse AvatarUploadResponse

func (response UploadAvatar201JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type UploadAvatar400JSONResponse Error

func (response UploadAvatar400JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UploadAvatar401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UploadAvatar401JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UploadAvatar413JSONResponse FileTooLargeError

func (response UploadAvatar413JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type UploadAvatar429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response UploadAvatar429JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type UploadAvatar500JSONResponse struct{ InternalErrorJSONResponse }

func (response UploadAvatar500JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UploadAvatar503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response UploadAvatar503JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAvatarByIdRequestObject struct {
	AvatarId AvatarIdPath `json:"avatar_id"`
	Params   DeleteAvatarByIdParams
}

type DeleteAvatarByIdResponseObject interface {
	VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error
}

type DeleteAvatarById204Response struct {
}

func (response DeleteAvatarById204Response) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAvatarById401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteAvatarById401JSONResponse) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAvatarById403JSONResponse Error

func (response DeleteAvatarById403JSONResponse) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAvatarById404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteAvatarById404JSONResponse) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAvatarById429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response DeleteAvatarById429JSONResponse) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAvatarById500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteAvatarById500JSONResponse) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAvatarById503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response DeleteAvatarById503JSONResponse) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarByIdRequestObject struct {
	AvatarId AvatarIdPath `json:"avatar_id"`
	Params   GetAvatarByIdParams
}

type GetAvatarByIdResponseObject interface {
	VisitGetAvatarByIdResponse(w http.ResponseWriter) error
}

type GetAvatarById200ResponseHeaders struct {
	CacheControl *string
	ETag         *string
}

type GetAvatarById200ImagejpegResponse struct {
	Body          io.Reader
	Headers       GetAvatarById200ResponseHeaders
	ContentLength int64
}

func (response GetAvatarById200ImagejpegResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetAvatarById200ImagepngResponse struct {
	Body          io.Reader
	Headers       GetAvatarById200ResponseHeaders
	ContentLength int64
}

func (response GetAvatarById200ImagepngResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetAvatarById200ImagewebpResponse struct {
	Body          io.Reader
	Headers       GetAvatarById200ResponseHeaders
	ContentLength int64
}

func (response GetAvatarById200ImagewebpResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/webp")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetAvatarById404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAvatarById404JSONResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarById429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response GetAvatarById429JSONResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarById500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetAvatarById500JSONResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarById503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetAvatarById503JSONResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarMetadataRequestObject struct {
	AvatarId AvatarIdPath `json:"avatar_id"`
}

type GetAvatarMetadataResponseObject interface {
	VisitGetAvatarMetadataResponse(w http.ResponseWriter) error
}

type GetAvatarMetadata200JSONResponse AvatarMetadata

func (response GetAvatarMetadata200JSONResponse) VisitGetAvatarMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarMetadata404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAvatarMetadata404JSONResponse) VisitGetAvatarMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarMetadata429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response GetAvatarMetadata429JSONResponse) VisitGetAvatarMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarMetadata500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetAvatarMetadata500JSONResponse) VisitGetAvatarMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarMetadata503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetAvatarMetadata503JSONResponse) VisitGetAvatarMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserAvatarRequestObject struct {
	UserId UserIdPath `json:"user_id"`
	Params DeleteUserAvatarParams
}

type DeleteUserAvatarResponseObject interface {
	VisitDeleteUserAvatarResponse(w http.ResponseWriter) error
}

type DeleteUserAvatar204Response struct {
}

func (response DeleteUserAvatar204Response) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteUserAvatar401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteUserAvatar401JSONResponse) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserAvatar403JSONResponse Error

func (response DeleteUserAvatar403JSONResponse) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserAvatar404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteUserAvatar404JSONResponse) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserAvatar429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response DeleteUserAvatar429JSONResponse) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserAvatar500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteUserAvatar500JSONResponse) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserAvatar503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response DeleteUserAvatar503JSONResponse) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserAvatarRequestObject struct {
	UserId UserIdPath `json:"user_id"`
	Params GetUserAvatarParams
}

type GetUserAvatarResponseObject interface {
	VisitGetUserAvatarResponse(w http.ResponseWriter) error
}

type GetUserAvatar200ResponseHeaders struct {
	CacheControl *string
	ETag         *string
}

type GetUserAvatar200ImagejpegResponse struct {
	Body          io.Reader
	Headers       GetUserAvatar200ResponseHeaders
	ContentLength int64
}

func (response GetUserAvatar200ImagejpegResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetUserAvatar200ImagepngResponse struct {
	Body          io.Reader
	Headers       GetUserAvatar200ResponseHeaders
	ContentLength int64
}

func (response GetUserAvatar200ImagepngResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetUserAvatar200ImagewebpResponse struct {
	Body          io.Reader
	Headers       GetUserAvatar200ResponseHeaders
	ContentLength int64
}

func (response GetUserAvatar200ImagewebpResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/webp")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetUserAvatar404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUserAvatar404JSONResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserAvatar429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response GetUserAvatar429JSONResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserAvatar500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetUserAvatar500JSONResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserAvatar503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetUserAvatar503JSONResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserAvatarsRequestObject struct {
	UserId UserIdPath `json:"user_id"`
	Params ListUserAvatarsParams
}

type ListUserAvatarsResponseObject interface {
	VisitListUserAvatarsResponse(w http.ResponseWriter) error
}

type ListUserAvatars200JSONResponse struct {
	Items *[]AvatarMetadata `json:"items,omitempty"`

	// Limit Example: 20
	Limit *int `json:"limit,omitempty"`

	// Offset Example: 0
	Offset *int `json:"offset,omitempty"`

	// Total Example: 3
	Total *int `json:"total,omitempty"`
}

func (response ListUserAvatars200JSONResponse) VisitListUserAvatarsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserAvatars404JSONResponse struct{ NotFoundJSONResponse }

func (response ListUserAvatars404JSONResponse) VisitListUserAvatarsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserAvatars429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response ListUserAvatars429JSONResponse) VisitListUserAvatarsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserAvatars500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListUserAvatars500JSONResponse) VisitListUserAvatarsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserAvatars503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response ListUserAvatars503JSONResponse) VisitListUserAvatarsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200JSONResponse HealthStatus

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type HealthCheck503JSONResponse HealthStatus

func (response HealthCheck503JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type LivenessCheckRequestObject struct {
}

type LivenessCheckResponseObject interface {
	VisitLivenessCheckResponse(w http.ResponseWriter) error
}

type LivenessCheck200JSONResponse LivenessStatus

func (response LivenessCheck200JSONResponse) VisitLivenessCheckResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LivenessCheck503JSONResponse LivenessStatus

func (response LivenessCheck503JSONResponse) VisitLivenessCheckResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetGalleryPageRequestObject struct {
	UserId UserIdPath `json:"user_id"`
}

type GetGalleryPageResponseObject interface {
	VisitGetGalleryPageResponse(w http.ResponseWriter) error
}

type GetGalleryPage200TexthtmlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetGalleryPage200TexthtmlResponse) VisitGetGalleryPageResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetGalleryPage404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGalleryPage404JSONResponse) VisitGetGalleryPageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUploadPageRequestObject struct {
}

type GetUploadPageResponseObject interface {
	VisitGetUploadPageResponse(w http.ResponseWriter) error
}

type GetUploadPage200TexthtmlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetUploadPage200TexthtmlResponse) VisitGetUploadPageResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostUploadFormRequestObject struct {
	Body *multipart.Reader
}

type PostUploadFormResponseObject interface {
	VisitPostUploadFormResponse(w http.ResponseWriter) error
}

type PostUploadForm200TexthtmlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostUploadForm200TexthtmlResponse) VisitPostUploadFormResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostUploadForm302Response struct {
}

func (response PostUploadForm302Response) VisitPostUploadFormResponse(w http.ResponseWriter) error {
	w.WriteHeader(302)
	return nil
}

type PostUploadForm400JSONResponse struct{ BadRequestJSONResponse }

func (response PostUploadForm400JSONResponse) VisitPostUploadFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// UploadAvatar Загрузка аватарки
	// (POST /api/v1/avatars)
	UploadAvatar(ctx context.Context, request UploadAvatarRequestObject) (UploadAvatarResponseObject, error)
	// DeleteAvatarById Удаление аватарки
	// (DELETE /api/v1/avatars/{avatar_id})
	DeleteAvatarById(ctx context.Context, request DeleteAvatarByIdRequestObject) (DeleteAvatarByIdResponseObject, error)
	// GetAvatarById Получение аватарки (бинарные данные изображения)
	// (GET /api/v1/avatars/{avatar_id})
	GetAvatarById(ctx context.Context, request GetAvatarByIdRequestObject) (GetAvatarByIdResponseObject, error)
	// GetAvatarMetadata Получение метаданных аватарки
	// (GET /api/v1/avatars/{avatar_id}/metadata)
	GetAvatarMetadata(ctx context.Context, request GetAvatarMetadataRequestObject) (GetAvatarMetadataResponseObject, error)
	// DeleteUserAvatar Удаление текущей аватарки пользователя
	// (DELETE /api/v1/users/{user_id}/avatar)
	DeleteUserAvatar(ctx context.Context, request DeleteUserAvatarRequestObject) (DeleteUserAvatarResponseObject, error)
	// GetUserAvatar Получение текущей аватарки пользователя
	// (GET /api/v1/users/{user_id}/avatar)
	GetUserAvatar(ctx context.Context, request GetUserAvatarRequestObject) (GetUserAvatarResponseObject, error)
	// ListUserAvatars Список аватарок пользователя
	// (GET /api/v1/users/{user_id}/avatars)
	ListUserAvatars(ctx context.Context, request ListUserAvatarsRequestObject) (ListUserAvatarsResponseObject, error)
	// HealthCheck Проверка работоспособности сервиса
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// LivenessCheck Проба жизнеспособности (liveness)
	// (GET /livez)
	LivenessCheck(ctx context.Context, request LivenessCheckRequestObject) (LivenessCheckResponseObject, error)
	// GetGalleryPage Галерея аватарок пользователя
	// (GET /web/gallery/{user_id})
	GetGalleryPage(ctx context.Context, request GetGalleryPageRequestObject) (GetGalleryPageResponseObject, error)
	// GetUploadPage Страница с формой загрузки аватарки
	// (GET /web/upload)
	GetUploadPage(ctx context.Context, request GetUploadPageRequestObject) (GetUploadPageResponseObject, error)
	// PostUploadForm Обработка загрузки через веб-форму
	// (POST /web/upload)
	PostUploadForm(ctx context.Context, request PostUploadFormRequestObject) (PostUploadFormResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// UploadAvatar operation middleware
func (sh *strictHandler) UploadAvatar(ctx echo.Context, params UploadAvatarParams) error {
	var request UploadAvatarRequestObject

	request.Params = params

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UploadAvatar(ctx.Request().Context(), request.(UploadAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadAvatar")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UploadAvatarResponseObject); ok {
		return validResponse.VisitUploadAvatarResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteAvatarById operation middleware
func (sh *strictHandler) DeleteAvatarById(ctx echo.Context, avatarId AvatarIdPath, params DeleteAvatarByIdParams) error {
	var request DeleteAvatarByIdRequestObject

	request.AvatarId = avatarId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAvatarById(ctx.Request().Context(), request.(DeleteAvatarByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAvatarById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteAvatarByIdResponseObject); ok {
		return validResponse.VisitDeleteAvatarByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAvatarById operation middleware
func (sh *strictHandler) GetAvatarById(ctx echo.Context, avatarId AvatarIdPath, params GetAvatarByIdParams) error {
	var request GetAvatarByIdRequestObject

	request.AvatarId = avatarId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAvatarById(ctx.Request().Context(), request.(GetAvatarByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAvatarById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAvatarByIdResponseObject); ok {
		return validResponse.VisitGetAvatarByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAvatarMetadata operation middleware
func (sh *strictHandler) GetAvatarMetadata(ctx echo.Context, avatarId AvatarIdPath) error {
	var request GetAvatarMetadataRequestObject

	request.AvatarId = avatarId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAvatarMetadata(ctx.Request().Context(), request.(GetAvatarMetadataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAvatarMetadata")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAvatarMetadataResponseObject); ok {
		return validResponse.VisitGetAvatarMetadataResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteUserAvatar operation middleware
func (sh *strictHandler) DeleteUserAvatar(ctx echo.Context, userId UserIdPath, params DeleteUserAvatarParams) error {
	var request DeleteUserAvatarRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUserAvatar(ctx.Request().Context(), request.(DeleteUserAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUserAvatar")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteUserAvatarResponseObject); ok {
		return validResponse.VisitDeleteUserAvatarResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUserAvatar operation middleware
func (sh *strictHandler) GetUserAvatar(ctx echo.Context, userId UserIdPath, params GetUserAvatarParams) error {
	var request GetUserAvatarRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserAvatar(ctx.Request().Context(), request.(GetUserAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserAvatar")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserAvatarResponseObject); ok {
		return validResponse.VisitGetUserAvatarResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListUserAvatars operation middleware
func (sh *strictHandler) ListUserAvatars(ctx echo.Context, userId UserIdPath, params ListUserAvatarsParams) error {
	var request ListUserAvatarsRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListUserAvatars(ctx.Request().Context(), request.(ListUserAvatarsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUserAvatars")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListUserAvatarsResponseObject); ok {
		return validResponse.VisitListUserAvatarsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(ctx echo.Context) error {
	var request HealthCheckRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx.Request().Context(), request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		return validResponse.VisitHealthCheckResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LivenessCheck operation middleware
func (sh *strictHandler) LivenessCheck(ctx echo.Context) error {
	var request LivenessCheckRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LivenessCheck(ctx.Request().Context(), request.(LivenessCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LivenessCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LivenessCheckResponseObject); ok {
		return validResponse.VisitLivenessCheckResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetGalleryPage operation middleware
func (sh *strictHandler) GetGalleryPage(ctx echo.Context, userId UserIdPath) error {
	var request GetGalleryPageRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetGalleryPage(ctx.Request().Context(), request.(GetGalleryPageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGalleryPage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetGalleryPageResponseObject); ok {
		return validResponse.VisitGetGalleryPageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUploadPage operation middleware
func (sh *strictHandler) GetUploadPage(ctx echo.Context) error {
	var request GetUploadPageRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUploadPage(ctx.Request().Context(), request.(GetUploadPageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUploadPage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUploadPageResponseObject); ok {
		return validResponse.VisitGetUploadPageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUploadForm operation middleware
func (sh *strictHandler) PostUploadForm(ctx echo.Context) error {
	var request PostUploadFormRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUploadForm(ctx.Request().Context(), request.(PostUploadFormRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUploadForm")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUploadFormResponseObject); ok {
		return validResponse.VisitPostUploadFormResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fz9bhvHdn+VwbZ/SMBSXEm0r6+A/uHEiaNe50KNbNy2iWGsuCNy7eXuZncpWzEESGQSO5Br1WmKXqC3",
	"TvoB9F9KMi1KIqlXmHmFPklxzsxyv4YSRSsuehMgCERyd+bM+fidz/FTreo1fM+lbhRqS0813wzMBo1o",
	"gJ9ubpiRGSxbK2ZUh88WDauB7Ue252pL2r17y7cI67AD1uEt1uHb7IT1NF2z4UcfXtE112xQbUkzcaEH",
	"tqXpWkC/bNoBtbSlKGhSXQurddowYfl1L2iYkbakNZv4ZLTpw8thFNhuTdva0rV7IQ2WrU+oadGgSBD7",
	"I3vDumzAW6zHv2Y9doKUDfk2YWdsyE75C3bEhpLgLjvlezphB3xX/MoGfI+/5N+xLjtkQ8KG7Ix1+Tbr",
	"8G9Zj7+MT1YXu4/O9rcloKq0fOvcs407i5q1U5xEzfhmSC9ke560LXg49D03pKgFH5jWZ/TLJg0j+FT1",
	"3Ii6+Kfp+45dNYHm8sMQCH+aWvYvA7quLWl/UU40rCx+DcsfBYEXiK1yB/831mUncFC+DX/xFhvwXXZM",
	"2BHrsDO+zYZ8R9vStWU3ooFrOmKli+miT8yG71D8U7wyWoKENNigARHfb+nvfIbv2YC3eQtPMECt2iNs",
	"yJ+zHtsHSRK+g4p1wHp8h3Vgy9970cde07WmO4mwU+J6EVnHVa7gED+xLt/hbb7NdwgbsC78r8OOhV7C",
	"Bqs02LCr9J5rbpi2Y64JkiYn3qKRaTshap4XmDW6RKp2UG3aEVkLqPmIBsQOiedTV9NHJ5Wbkog2fC8w",
	"A9vZJM0UBVcjPdblz2O5HSHCgaB6rA/ax1v8BZlZ8cKoFtDVv7mjk9VFwnrslPUI2wcNZScg3lmAFlCB",
	"vlADgJQB67I3cpE2OwOWFk8NkIPW3WcnQpN0AmunLADUqcVO2CkbsgF/xQaE74jXeFsnbJ912REA2FvW",
	"Y29Yhw1Yj+8RQGl2zPqsA4uyzhxhPwKICGRhPYCS3DYANkfsLevOfeECc+963qemuynxIJxW4p+ZESWO",
	"3bAjQp9UKbWopZOARsEmccwI0TWW+F3PIw3T3SRBvOcVyPhHFMwB3+XPQTgEhMf6wAHCn7EOyAc4zHcz",
	"7ABezRH2mh0ir4Gpz1C2PeAbGMYxvnnA26zLW2gxBEwIkRpsyHZrAQ3DEkAcoDv+dMpOhZ9BKR8QgAj2",
	"FvSE9Qn/B3bCjlCLzgDmgfAcfpAZEBMZ+SGdwFJSBwbSm/3P9g8oTbK8QlBxetK/dGZBtLp0ayjRz0AQ",
	"pZvrkdLJ/jfuDYvzHTwHOKMTNkSq2AlvswF7Q8BW2Fuh9WdZJeMvsmiu8EW2G9EaRdmBp3TNZlT3Avsr",
	"ak2rcSPuEHFQwJaRS0y0LbPVFSjaa95CFG1lFUOixaDg7FAZgTmHqBigN0N2ksgWIwe5bRKhfUoj0zIj",
	"pNMPPJ8GkS18dzWgZkStB2aUCbAsM6KlyG7QYpSla5bdoG5oe2540blvJU9u6dq67dAHIu5ICUHGfnMP",
	"/ZpqM9uaIPLTtYbdoA/Et+m17YZZo+WHPlWu7QdelYah7dYehJEZNfE81G02tKXPNZ+6FjyXfkzTMRx2",
	"aIRKsW7aDrW0+4qlQ/urLCnzxkLFMAw9OYrtRtcrCVkjlda1qN5srLlCMZ9qdkQbF3L6bvzKsrvu4Rpi",
	"VTMIzE343PStSwu66TueaSl4I34QDBF/X8SPOM5URrpJ6Pm5huJNotJEZ9IylvzV0+qbOWJCgrf2kFYj",
	"IEGYwj0k9zMZv16NQUyoowodm0KzmoGj4OL0HIb1RrRlOKpi4oex6q2ODpPlH43j7QKB4Ljd6uYDocxF",
	"rS+yx3s0Qt77+gWnkm+raL6VwassuXVq1+qRmqDHtiVyr4LTyW4tntPjtVQkjLKQ7O4j96Ng1zhG5jbP",
	"syfZ82PboXc9744Z1OiY/Ud7JIgJb5HI84gD7ymh1nzyQAFvlRvXfnN9EnxTHiC1rOosn1DTierjdC5X",
	"osj8thZ4j0SYch585tUavJwZmWumgIhLvhouXvqlLcWhxxiERWuBBFzLe+xObBp6mk8qJt+xN6hLw3Ac",
	"mwNqyghqAmgTpF6GPhVJWbdWoKightq8YTyZNwxtYuDM0yL8CjxbpAcOSqvNwI42V0GQgghRp7nZvKI6",
	"DZFVJUgEO/wVRoZ7GPZnw74TkVPgG5lKFDvWiSwu7PM2Fqx6/BvCDtgp6yA5p/wF/xZSj+0kh2edSepX",
	"cVTh27+jmyKgtaVkIOg2qwil8sXbnl9fCTxw4eQuNRtaMfz9E7BEJk+jjGV0LDww3+ZtdsROWE8n/BuZ",
	"WHVFxqrD0ffxu32Z8fYgSZIZMjDwGXyTrkFCuKzmPeRnMuUtyuVFmpy3rINxOv8adx2KhA8EzF8CSW9Y",
	"D1JupELH3fgOrE8wHzzEXEjmO0NM/TFBPAMB8RYuus36kFz2ce02pASC5DYcSKRIqUOJzA1zeaWy8fZY",
	"dZsj7J+RuF5uxXxJBzPErJhECocJC7DhTbwAUNfDjYRs3sZJcEnqMJzjOaSCIrWM7MjJK4wsWcX1nJsr",
	"y5qubdAgFJozP2fMGaBQnk9d07e1JW1xzphbhHDdjOpomGXTt8sb82WRYAhA80SRMqeG/1KQrJr+87j4",
	"X8iqU2DRMNZTvgeLxQa8uqgDz7pYZhFVlwHfZV2Rex+QpGQktDDWmdSCseITkSuzQ1A01gHFQYhIlZfw",
	"PTzCd5L8Y8LOeJvtY3J/IlJNpA2f3Oe7oDgpVOlgTWuAews1HUrdxaJPUjdifSSjh7J/ybfJjIRhnSwa",
	"xpNFw5A1BMBuzMWXLcilMRQXgka5Ja2Fz9XuM3mknKn0b90XKE7D6APP2szVABpNJ7J9M4jKEJuU4kQ4",
	"Sd2zTgXUT6EjsXxVmsH3yMxfr3x0Wycrv7+tkz/QtZVZlHWHnYjCIG+zPpk3Pv1AS0VIa7ZrBpvaRf4R",
	"CVJ4o6180T5fmF8w5i9XDkknP9qCsVApGfMlY/6uYSzhf3+viWRHu3bNoDcqhlGiC79dK1XmrUrJ/M38",
	"9VKlcv36tWsVyHSNJKtYyiY66Ijz1lmecMlRmoN/leYXFicvwygzQFVV5h9TQMjbfAfd63NZrELDG/A9",
	"RAkJ7mjSB+hCBmiIQ0B64cUBDQdgnzlXxdtAecUwpi1ZrTZ93wsiahGhUeESeejTmk58t6aTx3TNTxWu",
	"lt0N07EtguAqNfAK6lfj2jGxEwM2wge0HdHKqAitVO030t5yvs5WmV+crvVRyGeS9CXOWSZmQzGjUrFk",
	"BBRnqSKy9CpvIFQDjUKo7QtWiWAFHMM2HnXhtxfzJ19n39K1a0KTzn8v2xbDtxYvfkvRysFguNloAIBl",
	"POgRdrAUbd/IrAGyyzpMqN2HJfIo8HTUCd4Syu7QSIXG36ebsoK3fb7HDrHg3CW8je7pNHHcWFAWbRo0",
	"0FfsBzIjJdFBH3qAfvFAikrsDFA4K8w87zkv7TUzJIHXja1iCPT02BFZXVS5yVtIieDaB5vL1qVdZaZL",
	"v6VP41ozTqWikMc5iBkfnL8SfcHp7N9YnBYm/85rkqrpEs91NqVYyabXDIj32CVxbJgA5cdesGZbFnWv",
	"pI+E9r6LmUknUQERwfNnGHAOITBLmYs4buViHo16wv9fQeM/80Y6CWjoWo2iAmSt5DaNrtJEcnL8jzid",
	"Zl0Fao+JCeOE+ssmxShPpsWyxJColkXXzaYDIZcX2DXbNR1QR1lHSQoaMpQGfIgfU5VWJqE97ZwvRbsM",
	"HNLUx4TKJouPIR4GHwrqimCSj35SHZtMjD5J0CzeBQqmfBXJvuS7RaN/JZIyvi3Tu0yuN5bdqf7qh2a1",
	"Tksfem4UeE6WnqTS1TCflMwa/asb1yuqeteWrn1016yNe/sLzZxfW6guWpUvNNWhfjEY9OOorDIOhcgM",
	"27+8RGeniHjKjVSf9nyUG3V03w3pLrbH6We4coSqLOVPimJIwQn8klWxUC3i35znJUfMzmgaJMph+anM",
	"nLek5mXDa1XICXHgO1Vn/vwDzl/jw/cZH2K19YS3saJ5XATqc0ZfYwsBVctEkTmBxLXwcyrmBJsmrXxH",
	"oCsRLEuXrO1iwfQAmwTfxbUAbARMXH7Xx9feD/B7MVI6ceVdtAx4Gxc65c9kMfelKgO9TaOrw4L/k5D4",
	"11j2/cWyZKbQmlKb0SnOOw9JVjVZZ/Y9RcO/Br3Pfg5ovTDyCMeGt3fsMIU04c8BNThUrMaaBQOrw3YD",
	"QGDegE+2Kz+pxljUG3jr6yEds0N6SUOx5LuG49lG1mhwcKIJwny4XhwhFKxLm92CoRpflBxIP6h8LvIi",
	"08k8tqicFlL0vXIo9e+ytIu9/cma/XzvlxNHTccetWXXcRIrZcGKyfmhCEniwnz2QkN8QyJ7QaI06nDj",
	"6DNESSR3X0Lci8m1tAuxipgU+7BOq4+0qawp3Q7NzJUlk2TpScZrqS6n9yg/OJZ+crHwpJgTSz8zv5B7",
	"aKv40kQpR2ZgTm0yqWCyR9gBhJfK2yzxPI1oW3b4S94i/Dn+2QJ5phT1all7fWLWVsawNq7pVz3XpVWg",
	"hUR2g3rNKN2clve60qzGwbWrY/ZrORGUmuvP3Y3AD320xYGc4cG2UOFCEN8tOPPE4kQWmQhriHmxuJmy",
	"H9seyDN7vyyxdHESaeqOvUG/Gm/p34upn1O85YLViiFvEQkQMoGRwWGc9IhJmBMibrtgut5jffUdqj3W",
	"nyPstZgr4q94i1wzFgnyZcQ07MWLARkxT7WHK/Z00U/DznQ8ZnUYvzDk32IGF19by2RSsFDcEhwiTS3+",
	"Ih6S6bA+mUFiT/g2Zu1DOZ+DUurF8zn4ZRa7hqw/O0fYH4VABN6mJnDYAXHk9OVK4K1R8rvmGg1cGtFw",
	"SVKdkrDSSjFsS5aJBxUO5DgaTgjt811kP3yF58veP2N9kRfK+zt4BacNigpfI0Dwb3BoEEfVeug8UAI4",
	"w9fBKkZx0WPVtbZYE9kr9oMq5YxnUa8GyKeC0Nw47LhrYok6jTU8eSHy0iAZD9xqZuNLn6RAzA5J1fFC",
	"nAGeErMufboYjRQ2gibUV9phMoia6LpCwdSYtg86+xazTIGYKiybiTV+dhyONWgU2FXQHPj0mK6Va6bj",
	"0GAzyUzOK7jfFg+vmDg+Mn1CcnFwH9EnUbkeNZwL8tS8pD65++mdEhpXfO0Qp3t3CDsU9TNkdyGvu+Lg",
	"OCvBf0p2xqmIy0edf6BrUoAgMnHN6Dw5ibkuKab3zelRS3UY30VPDS4X4vFLvn9eyV9wSR9NtmbZAkG2",
	"4MvHXtDQfoYpyQuLSpe4mfQOg45XJWD2EwATb+OMfEs0yPPSmAEtmE3qV3JYvxePwCFUpiyPvwQuLBoL",
	"iiDqp/yreCU4o2DgfNN23MsMlGdaH0rdG80Ynm/IqX/FIaeur3Mj9p0iS0bTjkdYjmb7pdEUe7to0niP",
	"ItiIMTTHkn/FoKmD6DDACAu+SFXZMb4Sl9kzk/+j0dJ6FPlL5bLjVU2n7oXR0g3jhqEY61gJPKspPOrM",
	"srh5DbJLYi8suvfnSJ06jXLN8+u+mE4vb5hOk4YlP/CsuU2z4cxm9g6XynGpa06687mq10AXIFnxtJgi",
	"pK9w9BSXH1I3AEZT4L3iWFkeapPKVFxVU8yI5HcH35HFnA7ri8m5EefBgXfPA3K5rageKDadvt8pV04V",
	"q86rQ0ydFcltZDCh2OR7VHUc92thxeNrccefzKyu3CTlZMWuLKAfE/mPfrzBryBjOJxNdgL72Lq/9b8B",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
