// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AvatarMetadataProcessingStatus.
const (
	AvatarMetadataProcessingStatusCompleted  AvatarMetadataProcessingStatus = "completed"
	AvatarMetadataProcessingStatusFailed     AvatarMetadataProcessingStatus = "failed"
	AvatarMetadataProcessingStatusPending    AvatarMetadataProcessingStatus = "pending"
	AvatarMetadataProcessingStatusProcessing AvatarMetadataProcessingStatus = "processing"
)

// Valid indicates whether the value is a known member of the AvatarMetadataProcessingStatus enum.
func (e AvatarMetadataProcessingStatus) Valid() bool {
	switch e {
	case AvatarMetadataProcessingStatusCompleted:
		return true
	case AvatarMetadataProcessingStatusFailed:
		return true
	case AvatarMetadataProcessingStatusPending:
		return true
	case AvatarMetadataProcessingStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for AvatarMetadataUploadStatus.
const (
	AvatarMetadataUploadStatusFailed    AvatarMetadataUploadStatus = "failed"
	AvatarMetadataUploadStatusUploaded  AvatarMetadataUploadStatus = "uploaded"
	AvatarMetadataUploadStatusUploading AvatarMetadataUploadStatus = "uploading"
)

// Valid indicates whether the value is a known member of the AvatarMetadataUploadStatus enum.
func (e AvatarMetadataUploadStatus) Valid() bool {
	switch e {
	case AvatarMetadataUploadStatusFailed:
		return true
	case AvatarMetadataUploadStatusUploaded:
		return true
	case AvatarMetadataUploadStatusUploading:
		return true
	default:
		return false
	}
}

// Defines values for AvatarUploadResponseStatus.
const (
	AvatarUploadResponseStatusCompleted  AvatarUploadResponseStatus = "completed"
	AvatarUploadResponseStatusFailed     AvatarUploadResponseStatus = "failed"
	AvatarUploadResponseStatusProcessing AvatarUploadResponseStatus = "processing"
)

// Valid indicates whether the value is a known member of the AvatarUploadResponseStatus enum.
func (e AvatarUploadResponseStatus) Valid() bool {
	switch e {
	case AvatarUploadResponseStatusCompleted:
		return true
	case AvatarUploadResponseStatusFailed:
		return true
	case AvatarUploadResponseStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for ComponentStatusStatus.
const (
	ComponentStatusStatusError ComponentStatusStatus = "error"
	ComponentStatusStatusOk    ComponentStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the ComponentStatusStatus enum.
func (e ComponentStatusStatus) Valid() bool {
	switch e {
	case ComponentStatusStatusError:
		return true
	case ComponentStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusDegraded HealthStatusStatus = "degraded"
	HealthStatusStatusDown     HealthStatusStatus = "down"
	HealthStatusStatusOk       HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusDegraded:
		return true
	case HealthStatusStatusDown:
		return true
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for GetAvatarByIdParamsSize.
const (
	GetAvatarByIdParamsSizeN100x100 GetAvatarByIdParamsSize = "100x100"
	GetAvatarByIdParamsSizeN300x300 GetAvatarByIdParamsSize = "300x300"
	GetAvatarByIdParamsSizeOriginal GetAvatarByIdParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetAvatarByIdParamsSize enum.
func (e GetAvatarByIdParamsSize) Valid() bool {
	switch e {
	case GetAvatarByIdParamsSizeN100x100:
		return true
	case GetAvatarByIdParamsSizeN300x300:
		return true
	case GetAvatarByIdParamsSizeOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetAvatarByIdParamsFormat.
const (
	GetAvatarByIdParamsFormatJpeg GetAvatarByIdParamsFormat = "jpeg"
	GetAvatarByIdParamsFormatPng  GetAvatarByIdParamsFormat = "png"
	GetAvatarByIdParamsFormatWebp GetAvatarByIdParamsFormat = "webp"
)

// Valid indicates whether the value is a known member of the GetAvatarByIdParamsFormat enum.
func (e GetAvatarByIdParamsFormat) Valid() bool {
	switch e {
	case GetAvatarByIdParamsFormatJpeg:
		return true
	case GetAvatarByIdParamsFormatPng:
		return true
	case GetAvatarByIdParamsFormatWebp:
		return true
	default:
		return false
	}
}

// Defines values for GetUserAvatarParamsSize.
const (
	GetUserAvatarParamsSizeN100x100 GetUserAvatarParamsSize = "100x100"
	GetUserAvatarParamsSizeN300x300 GetUserAvatarParamsSize = "300x300"
	GetUserAvatarParamsSizeOriginal GetUserAvatarParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetUserAvatarParamsSize enum.
func (e GetUserAvatarParamsSize) Valid() bool {
	switch e {
	case GetUserAvatarParamsSizeN100x100:
		return true
	case GetUserAvatarParamsSizeN300x300:
		return true
	case GetUserAvatarParamsSizeOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetUserAvatarParamsFormat.
const (
	GetUserAvatarParamsFormatJpeg GetUserAvatarParamsFormat = "jpeg"
	GetUserAvatarParamsFormatPng  GetUserAvatarParamsFormat = "png"
	GetUserAvatarParamsFormatWebp GetUserAvatarParamsFormat = "webp"
)

// Valid indicates whether the value is a known member of the GetUserAvatarParamsFormat enum.
func (e GetUserAvatarParamsFormat) Valid() bool {
	switch e {
	case GetUserAvatarParamsFormatJpeg:
		return true
	case GetUserAvatarParamsFormatPng:
		return true
	case GetUserAvatarParamsFormatWebp:
		return true
	default:
		return false
	}
}

// AvatarMetadata defines model for AvatarMetadata.
type AvatarMetadata struct {
	CreatedAt  time.Time   `json:"created_at"`
	Dimensions *Dimensions `json:"dimensions,omitempty"`

	// FileName Example: avatar.jpg
	FileName string             `json:"file_name"`
	Id       openapi_types.UUID `json:"id"`

	// MimeType Example: image/jpeg
	MimeType         string                          `json:"mime_type"`
	ProcessingStatus *AvatarMetadataProcessingStatus `json:"processing_status,omitempty"`

	// Size Example: 1024000
	Size         int64                       `json:"size"`
	Thumbnails   *[]ThumbnailInfo            `json:"thumbnails,omitempty"`
	UpdatedAt    time.Time                   `json:"updated_at"`
	UploadStatus *AvatarMetadataUploadStatus `json:"upload_status,omitempty"`
	UserId       string                      `json:"user_id"`
}

// AvatarMetadataProcessingStatus defines model for AvatarMetadata.ProcessingStatus.
type AvatarMetadataProcessingStatus string

// AvatarMetadataUploadStatus defines model for AvatarMetadata.UploadStatus.
type AvatarMetadataUploadStatus string

// AvatarUploadResponse defines model for AvatarUploadResponse.
type AvatarUploadResponse struct {
	CreatedAt time.Time                  `json:"created_at"`
	Id        openapi_types.UUID         `json:"id"`
	Status    AvatarUploadResponseStatus `json:"status"`
	Url       string                     `json:"url"`
	UserId    string                     `json:"user_id"`
}

// AvatarUploadResponseStatus defines model for AvatarUploadResponse.Status.
type AvatarUploadResponseStatus string

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus struct {
	Error     *string               `json:"error,omitempty"`
	LatencyMs *int                  `json:"latency_ms,omitempty"`
	Status    ComponentStatusStatus `json:"status"`
}

// ComponentStatusStatus defines model for ComponentStatus.Status.
type ComponentStatusStatus string

// Dimensions defines model for Dimensions.
type Dimensions struct {
	Height int `json:"height"`
	Width  int `json:"width"`
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// FileTooLargeError defines model for FileTooLargeError.
type FileTooLargeError struct {
	// Error Example: File too large
	Error string `json:"error"`

	// MaxSize Example: 10485760
	MaxSize int64 `json:"max_size"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Components struct {
		Broker   *ComponentStatus `json:"broker,omitempty"`
		Database *ComponentStatus `json:"database,omitempty"`
		S3       *ComponentStatus `json:"s3,omitempty"`
	} `json:"components"`
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// ThumbnailInfo defines model for ThumbnailInfo.
type ThumbnailInfo struct {
	// Size Example: 100x100
	Size string `json:"size"`
	Url  string `json:"url"`
}

// AvatarIdPath defines model for AvatarIdPath.
type AvatarIdPath = openapi_types.UUID

// UserIdHeader defines model for UserIdHeader.
type UserIdHeader = string

// UserIdPath defines model for UserIdPath.
type UserIdPath = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UploadAvatarMultipartBody defines parameters for UploadAvatar.
type UploadAvatarMultipartBody struct {
	// File Файл изображения (JPEG, PNG, WebP), максимум 10MB
	File openapi_types.File `json:"file"`
}

// UploadAvatarParams defines parameters for UploadAvatar.
type UploadAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию
	XUserID UserIdHeader `json:"X-User-ID"`
}

// DeleteAvatarByIdParams defines parameters for DeleteAvatarById.
type DeleteAvatarByIdParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию
	XUserID UserIdHeader `json:"X-User-ID"`
}

// GetAvatarByIdParams defines parameters for GetAvatarById.
type GetAvatarByIdParams struct {
	// Size Требуемый размер изображения
	Size *GetAvatarByIdParamsSize `form:"size,omitempty" json:"size,omitempty"`

	// Format Требуемый формат изображения
	Format *GetAvatarByIdParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetAvatarByIdParamsSize defines parameters for GetAvatarById.
type GetAvatarByIdParamsSize string

// GetAvatarByIdParamsFormat defines parameters for GetAvatarById.
type GetAvatarByIdParamsFormat string

// DeleteUserAvatarParams defines parameters for DeleteUserAvatar.
type DeleteUserAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию
	XUserID UserIdHeader `json:"X-User-ID"`
}

// GetUserAvatarParams defines parameters for GetUserAvatar.
type GetUserAvatarParams struct {
	Size   *GetUserAvatarParamsSize   `form:"size,omitempty" json:"size,omitempty"`
	Format *GetUserAvatarParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetUserAvatarParamsSize defines parameters for GetUserAvatar.
type GetUserAvatarParamsSize string

// GetUserAvatarParamsFormat defines parameters for GetUserAvatar.
type GetUserAvatarParamsFormat string

// ListUserAvatarsParams defines parameters for ListUserAvatars.
type ListUserAvatarsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostUploadFormMultipartBody defines parameters for PostUploadForm.
type PostUploadFormMultipartBody struct {
	File   openapi_types.File `json:"file"`
	UserId *string            `json:"user_id,omitempty"`
}

// UploadAvatarMultipartRequestBody defines body for UploadAvatar for multipart/form-data ContentType.
type UploadAvatarMultipartRequestBody UploadAvatarMultipartBody

// PostUploadFormMultipartRequestBody defines body for PostUploadForm for multipart/form-data ContentType.
type PostUploadFormMultipartRequestBody PostUploadFormMultipartBody

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FvrbhvHFX6VwbY/bGApLkXacQX0hy+xo9YJ1MhG2iaGseKOyLXJ3c3u0LZiEJDIJHbgwKrTFC3QNEkv",
	"D0DJYkRLIvUKM6/QJynOmb1zSFG0ckFbwDDI5c7MuZ/vnDl6rFXdpuc61GGBtvRY80zfbFJGffx2+YHJ",
	"TH/ZWjFZHb5bNKj6tsds19GWtNu3l68R3uO7vCc6vCc2+QEfaLpmw48eLNE1x2xSbUkzcaO7tqXpmk8/",
	"bNk+tbQl5reorgXVOm2asP266zdNpi1prRa+yTY8WBww33ZqWruta7cD6i9bb1HTov44QfwvfI/3+VB0",
	"+EB8zAf8ACkbiU3Cj/mIH4rP+T4fhQT3+aHY1gnfFc/kr3wotsVz8Rnv85d8RPiIH/O+2OQ98SkfiOcR",
	"Z3V5eszbbwtAVWH52lTeJvGiFu0cnKgF3wroiWLPk9aGlwPPdQKKVnDFtN6lH7ZowOBb1XUYdfCj6XkN",
	"u2oCzcV7ARD+OLXtz326ri1pPysmFlaUvwbFN33f9eVROcb/xvv8ABgVm/BJdPhQPOOvCN/nPX4sNvlI",
	"bGltXVt2GPUdsyF3Opku+shseg2KH+WSeAsSUP8B9Yl83tZfm4cv+FB0RQc5GKJVbRM+Ek/5gO+AJonY",
	"QsPa5QOxxXtw5Dsuu+62HGs+TqSfEsdlZB13OQMmvuV9sSW6YlNsET7kffivx19Ju4QDbjtmi9Vd3/6I",
	"npJsizLTbgRp3yHSq4gdkNhQ9Zi/zFFnwNvXooO8wf8dviu6vC86hA/4IR8gszkT7POhNMCXGCfA70b8",
	"gCSe346JSsXNtykzLZMhnZ7vetRntvSoqk9NRq27JsuEPctktMDsJh2Pfbpm2U3qBLbrBCfxfS15s61r",
	"63aD3pXRIKWEMCIv3PNqqsNsa4Z4rGtNu0nvyqfpve2mWaPFex5V7u35bpUGge3U7gbMZC3khzqtprb0",
	"vuZRx4L30q9pOiapBmVoFOum3aCWdkexdWB/lCWlZCxWDMPQE1Zsh12sJGTZDqM1il7P6q3mmiMN87Fm",
	"M9o8UdK3oiXLzrqLe8hdTd83N+B7y7NOreiW13BNSyEb+YMUiPx8kjyi6K/MP0lCeF9D9Sa5IrGZtI5D",
	"+epp882wmJDgrt2jVQYkSFe4jeS+G2aVs3GIGW1UYWNzWFbLbyikOL+EYb+YtoxEVUK8GpneasxMVn40",
	"yoJjBDZMRp3qxl1pzONWPy4e934cee/oJ3AVrlbRfC0Tr7Lk1qldqzM1QQ9tSyKi/E+5o+V7erSXioQY",
	"G2RPj9OPQlyTBJk7PC+e5MzrdoPect2bpl+jE86Pz0giJqwizHVJA9YpQ6356K4ivFUuXXjj4izxTclA",
	"alsVL29Rs8Hqk2wuVzhkflvz3fsSoU8Ln3mzhixnMnPNlCHilEuD8qkXtRVMT3AIi9b8MOBa7kNnZtfQ",
	"03JSCTmbQ8YkOaZzrWQYj0qGoc0cpfKEySAO747TAwKg1ZZvs41VkJokQpYql1tnVKqQsLDq8z3eEy8Q",
	"hm0TvpvHWAeAOvfkikwxxl/pJMTXO6KLNdtAfEL4Lj/kPSTnUHwuPgWkvZnAWN6bpYSLUrhn/5puSPRo",
	"h5oBhGtWMW6FC2+4Xn3FdyFfklvUbGrjWPMrEImsWxLQH7OFDItN0eX7UD3rRHwCTCIGHfIBFqgjvoPP",
	"dvhIdOAtwgcEn+yjAJ/Ak3QZDthULXve568WCP9GqZfP0+R8x3sIisXHeOoIHvMeKFg8B5L2+IAPQyp0",
	"PE1swf5EPAnrZ8TWIyRnCLyAMo9BQaKDm27yI/GM8CPcuwv4W5LcBYZEB8hJMYW/AkSfYGyiO9HcFgj/",
	"ExI3yO2Yr2rIvze/JFk1AXXfyeoAxLAXbQDUDfAgqZvvpL54vxDaMPDxlB+I7sIHDliVzRp5gwmrtlXq",
	"P7CrlFxeWdZ07QH1A2k5pQVjwQCDcj3qmJ6tLWnlBWOhDNjYZHV0zKLp2cUHpaJE8zIQu7JOz5nhn8c0",
	"q6Z/mhT/haI6BBGNIjsV27BZ5MCrZR1k1gcJo7CGWL73UbJ8l6y4Aav5dPU3N6UVRjaT2jAyfIImMuAv",
	"wdB4DwwHQ8SONHBQEq5DFj4LyX9F+LHo8h1QNgg/pg3f3BHPwHBSUaUntmB7PFua6Si0XT6S3hURc4Rk",
	"DFD3z8UmOReGYZ2UDeNR2TDOS0VD7MbCd9mCwhVxr1Q06i3prr2vzlXJK8VMs6t9R0ZxGrArrrWRK7ib",
	"rQazPdNnRQAChajqTOrkbFIB81PYSKRflWWIbXLuVytv3tDJyjs3dPIeXVs5j7ru8QMU4pHo8iNSMt6+",
	"oqXgyJrtmP6GdlKyRIIU2aid71vle1OLRul0vYd0paEtGouVglEqGKVbhrGE/36vycpCu3DBoJcqhlGg",
	"i79YK1RKVqVgvlG6WKhULl68cKECZaWRQPilbFWBiTjvncUZt4xrCvxUKC2WZ+95KMstVQvkD6lAKLpi",
	"C9PrU3AAgm22AfatIEqEwR1dehdTyBAdcQSRXmZxiIZD8M9cqhJdoLxiGPP2h1Zbnuf6jFpEWlSwRO55",
	"tKYTz6np5CFd81JdomXngdmwLYLBNbTAM2gWTepIRkkMxAhf0HdkN68irVJ1Xmy9xXxTq1Iqz9f9Gyse",
	"klohKhBmFsN4+aISSRwojlEmu+KZeBpllT2AamBRGGqPpKgkWIHEsAmsXpAWMV0+2Q4vItNWswnRJJPO",
	"9rGjqriGYGYNwmzYgQi0O7BF3iUfxzcTbWl5DcpUofGL9CWBZPRIbPOXYBmQwLqYKw6TLIrtauzvDtBb",
	"XvAvyblQLD1MaLuYpHZDucmTIS6dlz6XT2OnTmEZkiAFRiY6AnoGfJ+sllU56xpSIqV2ZWPZOnXeytwa",
	"tfV58lwmwlcU+pgSviLGxQvZp57PGY3yvDHrd26LVE2HuE5jI1Qr2XBbPnEfOiQCaknUuu76a7ZlUecs",
	"YtU36HzPsEzoJSYg4bR4guhvBCgp5S6S3crJMorvKM7Eg/+Z95hZPFjXahS1kTXZG5Sdpb3mhPqPqNDk",
	"fUU8m4CWolLzwxZF/BMWjGHxnejZoutmqwFgxPXtmu2YDbCNsPOQlPohyARnjV5TdSBmoT2dtk5Fe5hS",
	"09RHhIa9fg/BD6ZlBXXjnp3HBamLgwx6nQVOyrVAwZxLkexTrh33wBeyXBGbYeGTqYImils2JFAqV81q",
	"nRauug7z3UaWnqQH1DQfFcwa/eWlixVVJ6ita2/eMmuTVn+gmaW1xWrZqnygqZj6cQLCN3H1PykkkHN8",
	"5/TiPT8HFig2U3d300NOfMv3emHnZOeY/7Y9R6jKbL9S1OxjEfknYxdjHQbxybT8EXOeUTsUV0HxcVht",
	"tUMzyKJAFTICuPJaFf1/Py76H4Yx2C47EF1sSb0aD2FTxncicwW9Z8BOTjpRM3NKy5Ng17uTb+n2Q9/O",
	"0hU257DjtYtd3s+iYg47uTP3T/XJzdNdfC7HYmZuncqer+jiRofiSdiNe66qWm5QdnaO+aMgt/9Drh8O",
	"cpFzY3cLajc6xJmtEcmaJu+d/4FA208Wm51hnDsxJwcTUdhNO0i5ffB9+H3DbtpM7fiLBvba7CZ4ZMmA",
	"b7YTflPdwKsPcNfXAzrhhPSWhmLL10WN2WuBeOZppuGnPKocn36Sokv7wKKhmrwKJZB+Ufkec5nZyLxW",
	"Vg46KG4RciHj72FvDm9KZ7s6Fds/EsKYj1a1m9VxoiPlTnnghdtiso7anHuy+S+6/BhgZAgrkos8nayW",
	"C/HlHY5QAn7AJmbqrk5OveZu68ayuJw4uVqn1fvaXKadvunJzKckEynpiagLqQsc935+ACX9ZnnsTTlv",
	"kn6ntJh7qT2+aCZknBm8UdtvCmYNCN8F4CWTlBwqHgBmkj14krqR6YnnokPEU/zYAX1KGy2fvWgvziza",
	"ygTRRh3Squs4tAq0EGY3qdti6Xs3mvhM9Cie1Tk7gX8dDjykZoTFFjb/wfkOACHAlyP0x2E4ooCN9iGO",
	"uaR8SDwby66J18mCJ1HYCEu4kez9R/4HOs1OkCfeLjkJ3f0hXSvWzEaD+htJUp3W0rghX14x8R5p/lx6",
	"cl5i9BEr1lmzcQLeyWvirVtv3yygMMOAI8d8tgh/KeswbHiOQZIzjutZ/f0xORlvZE4fo9+jaymVyeHe",
	"aXqSF7yhmn5oSccd5FH0dxmpCaax7HXK9dP6OFJKejzikhULpCQpl+uu39S+h3GJE4uTU8wDv8bEw1kp",
	"mH/L+3xfdHFYriPvA/LaOAdWcD6pg8KpvUF0F453mynPE89BCmVjUQEuvs0vHaI9pA0Eav60Hw8yk2WZ",
	"fpbS9uJhg+mOnPqLppy5fp2bteuNiyQee9jHtgbfKcTjbN1xl8aBSv9BFENzIvkrwqMeRoch3iTDg1S3",
	"BkstvG3KjgDGMyZ1xrylYrHhVs1G3Q3Y0iXjkqG4xVrxXauFSTSzNFgqQu21UHO9uifn0hbCRL9QdZsY",
	"yUOOHo/nxPRI5kAxzJia6IunugbjN9P5iJnURlFdp7jZyp8OKSAbOnr8SF6+xwLs8/0pE27JsRIyKw6d",
	"vxcd7pwql6aB77lhQHhMiAIUh3yBFosTAx2E+R9DshRb5NzqymVSTHbsh/2UVyT8O7Y9fDTgQ/7yfHIS",
	"mHn7Tvs/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
