// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AvatarMetadataProcessingStatus.
const (
	AvatarMetadataProcessingStatusCompleted  AvatarMetadataProcessingStatus = "completed"
	AvatarMetadataProcessingStatusFailed     AvatarMetadataProcessingStatus = "failed"
	AvatarMetadataProcessingStatusPending    AvatarMetadataProcessingStatus = "pending"
	AvatarMetadataProcessingStatusProcessing AvatarMetadataProcessingStatus = "processing"
)

// Valid indicates whether the value is a known member of the AvatarMetadataProcessingStatus enum.
func (e AvatarMetadataProcessingStatus) Valid() bool {
	switch e {
	case AvatarMetadataProcessingStatusCompleted:
		return true
	case AvatarMetadataProcessingStatusFailed:
		return true
	case AvatarMetadataProcessingStatusPending:
		return true
	case AvatarMetadataProcessingStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for AvatarMetadataUploadStatus.
const (
	AvatarMetadataUploadStatusFailed    AvatarMetadataUploadStatus = "failed"
	AvatarMetadataUploadStatusUploaded  AvatarMetadataUploadStatus = "uploaded"
	AvatarMetadataUploadStatusUploading AvatarMetadataUploadStatus = "uploading"
)

// Valid indicates whether the value is a known member of the AvatarMetadataUploadStatus enum.
func (e AvatarMetadataUploadStatus) Valid() bool {
	switch e {
	case AvatarMetadataUploadStatusFailed:
		return true
	case AvatarMetadataUploadStatusUploaded:
		return true
	case AvatarMetadataUploadStatusUploading:
		return true
	default:
		return false
	}
}

// Defines values for AvatarUploadResponseStatus.
const (
	AvatarUploadResponseStatusCompleted  AvatarUploadResponseStatus = "completed"
	AvatarUploadResponseStatusFailed     AvatarUploadResponseStatus = "failed"
	AvatarUploadResponseStatusProcessing AvatarUploadResponseStatus = "processing"
)

// Valid indicates whether the value is a known member of the AvatarUploadResponseStatus enum.
func (e AvatarUploadResponseStatus) Valid() bool {
	switch e {
	case AvatarUploadResponseStatusCompleted:
		return true
	case AvatarUploadResponseStatusFailed:
		return true
	case AvatarUploadResponseStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for ComponentStatusStatus.
const (
	ComponentStatusStatusError ComponentStatusStatus = "error"
	ComponentStatusStatusOk    ComponentStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the ComponentStatusStatus enum.
func (e ComponentStatusStatus) Valid() bool {
	switch e {
	case ComponentStatusStatusError:
		return true
	case ComponentStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusDegraded HealthStatusStatus = "degraded"
	HealthStatusStatusDown     HealthStatusStatus = "down"
	HealthStatusStatusOk       HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusDegraded:
		return true
	case HealthStatusStatusDown:
		return true
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for GetAvatarByIdParamsSize.
const (
	GetAvatarByIdParamsSizeN100x100 GetAvatarByIdParamsSize = "100x100"
	GetAvatarByIdParamsSizeN300x300 GetAvatarByIdParamsSize = "300x300"
	GetAvatarByIdParamsSizeOriginal GetAvatarByIdParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetAvatarByIdParamsSize enum.
func (e GetAvatarByIdParamsSize) Valid() bool {
	switch e {
	case GetAvatarByIdParamsSizeN100x100:
		return true
	case GetAvatarByIdParamsSizeN300x300:
		return true
	case GetAvatarByIdParamsSizeOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetAvatarByIdParamsFormat.
const (
	GetAvatarByIdParamsFormatJpeg GetAvatarByIdParamsFormat = "jpeg"
	GetAvatarByIdParamsFormatPng  GetAvatarByIdParamsFormat = "png"
	GetAvatarByIdParamsFormatWebp GetAvatarByIdParamsFormat = "webp"
)

// Valid indicates whether the value is a known member of the GetAvatarByIdParamsFormat enum.
func (e GetAvatarByIdParamsFormat) Valid() bool {
	switch e {
	case GetAvatarByIdParamsFormatJpeg:
		return true
	case GetAvatarByIdParamsFormatPng:
		return true
	case GetAvatarByIdParamsFormatWebp:
		return true
	default:
		return false
	}
}

// Defines values for GetUserAvatarParamsSize.
const (
	GetUserAvatarParamsSizeN100x100 GetUserAvatarParamsSize = "100x100"
	GetUserAvatarParamsSizeN300x300 GetUserAvatarParamsSize = "300x300"
	GetUserAvatarParamsSizeOriginal GetUserAvatarParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetUserAvatarParamsSize enum.
func (e GetUserAvatarParamsSize) Valid() bool {
	switch e {
	case GetUserAvatarParamsSizeN100x100:
		return true
	case GetUserAvatarParamsSizeN300x300:
		return true
	case GetUserAvatarParamsSizeOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetUserAvatarParamsFormat.
const (
	GetUserAvatarParamsFormatJpeg GetUserAvatarParamsFormat = "jpeg"
	GetUserAvatarParamsFormatPng  GetUserAvatarParamsFormat = "png"
	GetUserAvatarParamsFormatWebp GetUserAvatarParamsFormat = "webp"
)

// Valid indicates whether the value is a known member of the GetUserAvatarParamsFormat enum.
func (e GetUserAvatarParamsFormat) Valid() bool {
	switch e {
	case GetUserAvatarParamsFormatJpeg:
		return true
	case GetUserAvatarParamsFormatPng:
		return true
	case GetUserAvatarParamsFormatWebp:
		return true
	default:
		return false
	}
}

// AvatarMetadata defines model for AvatarMetadata.
type AvatarMetadata struct {
	CreatedAt  time.Time   `json:"created_at"`
	Dimensions *Dimensions `json:"dimensions,omitempty"`

	// FileName Example: avatar.jpg
	FileName string             `json:"file_name"`
	Id       openapi_types.UUID `json:"id"`

	// MimeType Example: image/jpeg
	MimeType         string                          `json:"mime_type"`
	ProcessingStatus *AvatarMetadataProcessingStatus `json:"processing_status,omitempty"`

	// Size Example: 1024000
	Size         int64                       `json:"size"`
	Thumbnails   *[]ThumbnailInfo            `json:"thumbnails,omitempty"`
	UpdatedAt    time.Time                   `json:"updated_at"`
	UploadStatus *AvatarMetadataUploadStatus `json:"upload_status,omitempty"`
	UserId       string                      `json:"user_id"`
}

// AvatarMetadataProcessingStatus defines model for AvatarMetadata.ProcessingStatus.
type AvatarMetadataProcessingStatus string

// AvatarMetadataUploadStatus defines model for AvatarMetadata.UploadStatus.
type AvatarMetadataUploadStatus string

// AvatarUploadResponse defines model for AvatarUploadResponse.
type AvatarUploadResponse struct {
	CreatedAt time.Time                  `json:"created_at"`
	Id        openapi_types.UUID         `json:"id"`
	Status    AvatarUploadResponseStatus `json:"status"`
	Url       string                     `json:"url"`
	UserId    string                     `json:"user_id"`
}

// AvatarUploadResponseStatus defines model for AvatarUploadResponse.Status.
type AvatarUploadResponseStatus string

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus struct {
	Error     *string               `json:"error,omitempty"`
	LatencyMs *int                  `json:"latency_ms,omitempty"`
	Status    ComponentStatusStatus `json:"status"`
}

// ComponentStatusStatus defines model for ComponentStatus.Status.
type ComponentStatusStatus string

// Dimensions defines model for Dimensions.
type Dimensions struct {
	Height int `json:"height"`
	Width  int `json:"width"`
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// FileTooLargeError defines model for FileTooLargeError.
type FileTooLargeError struct {
	// Error Example: File too large
	Error string `json:"error"`

	// MaxSize Example: 10485760
	MaxSize int64 `json:"max_size"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Components struct {
		Broker   *ComponentStatus `json:"broker,omitempty"`
		Database *ComponentStatus `json:"database,omitempty"`
		S3       *ComponentStatus `json:"s3,omitempty"`
	} `json:"components"`
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// ThumbnailInfo defines model for ThumbnailInfo.
type ThumbnailInfo struct {
	// Size Example: 100x100
	Size string `json:"size"`
	Url  string `json:"url"`
}

// AvatarIdPath defines model for AvatarIdPath.
type AvatarIdPath = openapi_types.UUID

// UserIdHeader defines model for UserIdHeader.
type UserIdHeader = string

// UserIdPath defines model for UserIdPath.
type UserIdPath = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UploadAvatarMultipartBody defines parameters for UploadAvatar.
type UploadAvatarMultipartBody struct {
	// File Файл изображения (JPEG, PNG, WebP), максимум 10MB
	File openapi_types.File `json:"file"`
}

// UploadAvatarParams defines parameters for UploadAvatar.
type UploadAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию
	XUserID UserIdHeader `json:"X-User-ID"`
}

// DeleteAvatarByIdParams defines parameters for DeleteAvatarById.
type DeleteAvatarByIdParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию
	XUserID UserIdHeader `json:"X-User-ID"`
}

// GetAvatarByIdParams defines parameters for GetAvatarById.
type GetAvatarByIdParams struct {
	// Size Требуемый размер изображения
	Size *GetAvatarByIdParamsSize `form:"size,omitempty" json:"size,omitempty"`

	// Format Требуемый формат изображения
	Format *GetAvatarByIdParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetAvatarByIdParamsSize defines parameters for GetAvatarById.
type GetAvatarByIdParamsSize string

// GetAvatarByIdParamsFormat defines parameters for GetAvatarById.
type GetAvatarByIdParamsFormat string

// DeleteUserAvatarParams defines parameters for DeleteUserAvatar.
type DeleteUserAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию
	XUserID UserIdHeader `json:"X-User-ID"`
}

// GetUserAvatarParams defines parameters for GetUserAvatar.
type GetUserAvatarParams struct {
	Size   *GetUserAvatarParamsSize   `form:"size,omitempty" json:"size,omitempty"`
	Format *GetUserAvatarParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetUserAvatarParamsSize defines parameters for GetUserAvatar.
type GetUserAvatarParamsSize string

// GetUserAvatarParamsFormat defines parameters for GetUserAvatar.
type GetUserAvatarParamsFormat string

// ListUserAvatarsParams defines parameters for ListUserAvatars.
type ListUserAvatarsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostUploadFormMultipartBody defines parameters for PostUploadForm.
type PostUploadFormMultipartBody struct {
	File   openapi_types.File `json:"file"`
	UserId *string            `json:"user_id,omitempty"`
}

// UploadAvatarMultipartRequestBody defines body for UploadAvatar for multipart/form-data ContentType.
type UploadAvatarMultipartRequestBody UploadAvatarMultipartBody

// PostUploadFormMultipartRequestBody defines body for PostUploadForm for multipart/form-data ContentType.
type PostUploadFormMultipartRequestBody PostUploadFormMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// UploadAvatar Загрузка аватарки
	// (POST /api/v1/avatars)
	UploadAvatar(ctx echo.Context, params UploadAvatarParams) error
	// DeleteAvatarById Удаление аватарки
	// (DELETE /api/v1/avatars/{avatar_id})
	DeleteAvatarById(ctx echo.Context, avatarId AvatarIdPath, params DeleteAvatarByIdParams) error
	// GetAvatarById Получение аватарки (бинарные данные изображения)
	// (GET /api/v1/avatars/{avatar_id})
	GetAvatarById(ctx echo.Context, avatarId AvatarIdPath, params GetAvatarByIdParams) error
	// GetAvatarMetadata Получение метаданных аватарки
	// (GET /api/v1/avatars/{avatar_id}/metadata)
	GetAvatarMetadata(ctx echo.Context, avatarId AvatarIdPath) error
	// DeleteUserAvatar Удаление текущей аватарки пользователя
	// (DELETE /api/v1/users/{user_id}/avatar)
	DeleteUserAvatar(ctx echo.Context, userId UserIdPath, params DeleteUserAvatarParams) error
	// GetUserAvatar Получение текущей аватарки пользователя
	// (GET /api/v1/users/{user_id}/avatar)
	GetUserAvatar(ctx echo.Context, userId UserIdPath, params GetUserAvatarParams) error
	// ListUserAvatars Список аватарок пользователя
	// (GET /api/v1/users/{user_id}/avatars)
	ListUserAvatars(ctx echo.Context, userId UserIdPath, params ListUserAvatarsParams) error
	// HealthCheck Проверка работоспособности сервиса
	// (GET /health)
	HealthCheck(ctx echo.Context) error
	// GetGalleryPage Галерея аватарок пользователя
	// (GET /web/gallery/{user_id})
	GetGalleryPage(ctx echo.Context, userId UserIdPath) error
	// GetUploadPage Страница с формой загрузки аватарки
	// (GET /web/upload)
	GetUploadPage(ctx echo.Context) error
	// PostUploadForm Обработка загрузки через веб-форму
	// (POST /web/upload)
	PostUploadForm(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// UploadAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) UploadAvatar(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadAvatarParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UploadAvatar(ctx, params)
	return err
}

// DeleteAvatarById converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAvatarById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAvatarByIdParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAvatarById(ctx, avatarId, params)
	return err
}

// GetAvatarById converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvatarById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAvatarByIdParams
	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", ctx.QueryParams(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter size: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvatarById(ctx, avatarId, params)
	return err
}

// GetAvatarMetadata converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvatarMetadata(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvatarMetadata(ctx, avatarId)
	return err
}

// DeleteUserAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserAvatar(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteUserAvatarParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserAvatar(ctx, userId, params)
	return err
}

// GetUserAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserAvatar(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserAvatarParams
	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", ctx.QueryParams(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter size: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserAvatar(ctx, userId, params)
	return err
}

// ListUserAvatars converts echo context to params.
func (w *ServerInterfaceWrapper) ListUserAvatars(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserAvatarsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUserAvatars(ctx, userId, params)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// GetGalleryPage converts echo context to params.
func (w *ServerInterfaceWrapper) GetGalleryPage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGalleryPage(ctx, userId)
	return err
}

// GetUploadPage converts echo context to params.
func (w *ServerInterfaceWrapper) GetUploadPage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUploadPage(ctx)
	return err
}

// PostUploadForm converts echo context to params.
func (w *ServerInterfaceWrapper) PostUploadForm(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUploadForm(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/api/v1/avatars", wrapper.UploadAvatar, options.OperationMiddlewares["uploadAvatar"]...)
	router.DELETE(options.BaseURL+"/api/v1/avatars/:avatar_id", wrapper.DeleteAvatarById, options.OperationMiddlewares["deleteAvatarById"]...)
	router.GET(options.BaseURL+"/api/v1/avatars/:avatar_id", wrapper.GetAvatarById, options.OperationMiddlewares["getAvatarById"]...)
	router.GET(options.BaseURL+"/api/v1/avatars/:avatar_id/metadata", wrapper.GetAvatarMetadata, options.OperationMiddlewares["getAvatarMetadata"]...)
	router.DELETE(options.BaseURL+"/api/v1/users/:user_id/avatar", wrapper.DeleteUserAvatar, options.OperationMiddlewares["deleteUserAvatar"]...)
	router.GET(options.BaseURL+"/api/v1/users/:user_id/avatar", wrapper.GetUserAvatar, options.OperationMiddlewares["getUserAvatar"]...)
	router.GET(options.BaseURL+"/api/v1/users/:user_id/avatars", wrapper.ListUserAvatars, options.OperationMiddlewares["listUserAvatars"]...)
	router.GET(options.BaseURL+"/health", wrapper.HealthCheck, options.OperationMiddlewares["healthCheck"]...)
	router.GET(options.BaseURL+"/web/upload", wrapper.GetUploadPage, options.OperationMiddlewares["getUploadPage"]...)
	router.POST(options.BaseURL+"/web/upload", wrapper.PostUploadForm, options.OperationMiddlewares["postUploadForm"]...)
	router.GET(options.BaseURL+"/web/gallery/:user_id", wrapper.GetGalleryPage, options.OperationMiddlewares["getGalleryPage"]...)

}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type UploadAvatarRequestObject struct {
	Params UploadAvatarParams
	Body   *multipart.Reader
}

type UploadAvatarResponseObject interface {
	VisitUploadAvatarResponse(w http.ResponseWriter) error
}

type UploadAvatar201JSONResponse AvatarUploadResponse

func (response UploadAvatar201JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type UploadAvatar400JSONResponse Error

func (response UploadAvatar400JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UploadAvatar401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UploadAvatar401JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UploadAvatar413JSONResponse FileTooLargeError

func (response UploadAvatar413JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type UploadAvatar500JSONResponse struct{ InternalErrorJSONResponse }

func (response UploadAvatar500JSONResponse) VisitUploadAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAvatarByIdRequestObject struct {
	AvatarId AvatarIdPath `json:"avatar_id"`
	Params   DeleteAvatarByIdParams
}

type DeleteAvatarByIdResponseObject interface {
	VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error
}

type DeleteAvatarById204Response struct {
}

func (response DeleteAvatarById204Response) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAvatarById401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteAvatarById401JSONResponse) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAvatarById403JSONResponse Error

func (response DeleteAvatarById403JSONResponse) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAvatarById404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteAvatarById404JSONResponse) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAvatarById500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteAvatarById500JSONResponse) VisitDeleteAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarByIdRequestObject struct {
	AvatarId AvatarIdPath `json:"avatar_id"`
	Params   GetAvatarByIdParams
}

type GetAvatarByIdResponseObject interface {
	VisitGetAvatarByIdResponse(w http.ResponseWriter) error
}

type GetAvatarById200ResponseHeaders struct {
	CacheControl *string
	ETag         *string
}

type GetAvatarById200ImagejpegResponse struct {
	Body          io.Reader
	Headers       GetAvatarById200ResponseHeaders
	ContentLength int64
}

func (response GetAvatarById200ImagejpegResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetAvatarById200ImagepngResponse struct {
	Body          io.Reader
	Headers       GetAvatarById200ResponseHeaders
	ContentLength int64
}

func (response GetAvatarById200ImagepngResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetAvatarById200ImagewebpResponse struct {
	Body          io.Reader
	Headers       GetAvatarById200ResponseHeaders
	ContentLength int64
}

func (response GetAvatarById200ImagewebpResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/webp")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetAvatarById404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAvatarById404JSONResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarById500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetAvatarById500JSONResponse) VisitGetAvatarByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarMetadataRequestObject struct {
	AvatarId AvatarIdPath `json:"avatar_id"`
}

type GetAvatarMetadataResponseObject interface {
	VisitGetAvatarMetadataResponse(w http.ResponseWriter) error
}

type GetAvatarMetadata200JSONResponse AvatarMetadata

func (response GetAvatarMetadata200JSONResponse) VisitGetAvatarMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarMetadata404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAvatarMetadata404JSONResponse) VisitGetAvatarMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAvatarMetadata500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetAvatarMetadata500JSONResponse) VisitGetAvatarMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserAvatarRequestObject struct {
	UserId UserIdPath `json:"user_id"`
	Params DeleteUserAvatarParams
}

type DeleteUserAvatarResponseObject interface {
	VisitDeleteUserAvatarResponse(w http.ResponseWriter) error
}

type DeleteUserAvatar204Response struct {
}

func (response DeleteUserAvatar204Response) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteUserAvatar401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteUserAvatar401JSONResponse) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserAvatar403JSONResponse Error

func (response DeleteUserAvatar403JSONResponse) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserAvatar404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteUserAvatar404JSONResponse) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserAvatar500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteUserAvatar500JSONResponse) VisitDeleteUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserAvatarRequestObject struct {
	UserId UserIdPath `json:"user_id"`
	Params GetUserAvatarParams
}

type GetUserAvatarResponseObject interface {
	VisitGetUserAvatarResponse(w http.ResponseWriter) error
}

type GetUserAvatar200ResponseHeaders struct {
	CacheControl *string
	ETag         *string
}

type GetUserAvatar200ImagejpegResponse struct {
	Body          io.Reader
	Headers       GetUserAvatar200ResponseHeaders
	ContentLength int64
}

func (response GetUserAvatar200ImagejpegResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetUserAvatar200ImagepngResponse struct {
	Body          io.Reader
	Headers       GetUserAvatar200ResponseHeaders
	ContentLength int64
}

func (response GetUserAvatar200ImagepngResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetUserAvatar200ImagewebpResponse struct {
	Body          io.Reader
	Headers       GetUserAvatar200ResponseHeaders
	ContentLength int64
}

func (response GetUserAvatar200ImagewebpResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/webp")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetUserAvatar404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUserAvatar404JSONResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserAvatar500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetUserAvatar500JSONResponse) VisitGetUserAvatarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserAvatarsRequestObject struct {
	UserId UserIdPath `json:"user_id"`
	Params ListUserAvatarsParams
}

type ListUserAvatarsResponseObject interface {
	VisitListUserAvatarsResponse(w http.ResponseWriter) error
}

type ListUserAvatars200JSONResponse struct {
	Items *[]AvatarMetadata `json:"items,omitempty"`

	// Limit Example: 20
	Limit *int `json:"limit,omitempty"`

	// Offset Example: 0
	Offset *int `json:"offset,omitempty"`

	// Total Example: 3
	Total *int `json:"total,omitempty"`
}

func (response ListUserAvatars200JSONResponse) VisitListUserAvatarsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserAvatars404JSONResponse struct{ NotFoundJSONResponse }

func (response ListUserAvatars404JSONResponse) VisitListUserAvatarsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserAvatars500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListUserAvatars500JSONResponse) VisitListUserAvatarsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200JSONResponse HealthStatus

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type HealthCheck503JSONResponse HealthStatus

func (response HealthCheck503JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetGalleryPageRequestObject struct {
	UserId UserIdPath `json:"user_id"`
}

type GetGalleryPageResponseObject interface {
	VisitGetGalleryPageResponse(w http.ResponseWriter) error
}

type GetGalleryPage200TexthtmlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetGalleryPage200TexthtmlResponse) VisitGetGalleryPageResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetGalleryPage404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGalleryPage404JSONResponse) VisitGetGalleryPageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUploadPageRequestObject struct {
}

type GetUploadPageResponseObject interface {
	VisitGetUploadPageResponse(w http.ResponseWriter) error
}

type GetUploadPage200TexthtmlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetUploadPage200TexthtmlResponse) VisitGetUploadPageResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostUploadFormRequestObject struct {
	Body *multipart.Reader
}

type PostUploadFormResponseObject interface {
	VisitPostUploadFormResponse(w http.ResponseWriter) error
}

type PostUploadForm200TexthtmlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostUploadForm200TexthtmlResponse) VisitPostUploadFormResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostUploadForm302Response struct {
}

func (response PostUploadForm302Response) VisitPostUploadFormResponse(w http.ResponseWriter) error {
	w.WriteHeader(302)
	return nil
}

type PostUploadForm400JSONResponse struct{ BadRequestJSONResponse }

func (response PostUploadForm400JSONResponse) VisitPostUploadFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// UploadAvatar Загрузка аватарки
	// (POST /api/v1/avatars)
	UploadAvatar(ctx context.Context, request UploadAvatarRequestObject) (UploadAvatarResponseObject, error)
	// DeleteAvatarById Удаление аватарки
	// (DELETE /api/v1/avatars/{avatar_id})
	DeleteAvatarById(ctx context.Context, request DeleteAvatarByIdRequestObject) (DeleteAvatarByIdResponseObject, error)
	// GetAvatarById Получение аватарки (бинарные данные изображения)
	// (GET /api/v1/avatars/{avatar_id})
	GetAvatarById(ctx context.Context, request GetAvatarByIdRequestObject) (GetAvatarByIdResponseObject, error)
	// GetAvatarMetadata Получение метаданных аватарки
	// (GET /api/v1/avatars/{avatar_id}/metadata)
	GetAvatarMetadata(ctx context.Context, request GetAvatarMetadataRequestObject) (GetAvatarMetadataResponseObject, error)
	// DeleteUserAvatar Удаление текущей аватарки пользователя
	// (DELETE /api/v1/users/{user_id}/avatar)
	DeleteUserAvatar(ctx context.Context, request DeleteUserAvatarRequestObject) (DeleteUserAvatarResponseObject, error)
	// GetUserAvatar Получение текущей аватарки пользователя
	// (GET /api/v1/users/{user_id}/avatar)
	GetUserAvatar(ctx context.Context, request GetUserAvatarRequestObject) (GetUserAvatarResponseObject, error)
	// ListUserAvatars Список аватарок пользователя
	// (GET /api/v1/users/{user_id}/avatars)
	ListUserAvatars(ctx context.Context, request ListUserAvatarsRequestObject) (ListUserAvatarsResponseObject, error)
	// HealthCheck Проверка работоспособности сервиса
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// GetGalleryPage Галерея аватарок пользователя
	// (GET /web/gallery/{user_id})
	GetGalleryPage(ctx context.Context, request GetGalleryPageRequestObject) (GetGalleryPageResponseObject, error)
	// GetUploadPage Страница с формой загрузки аватарки
	// (GET /web/upload)
	GetUploadPage(ctx context.Context, request GetUploadPageRequestObject) (GetUploadPageResponseObject, error)
	// PostUploadForm Обработка загрузки через веб-форму
	// (POST /web/upload)
	PostUploadForm(ctx context.Context, request PostUploadFormRequestObject) (PostUploadFormResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// UploadAvatar operation middleware
func (sh *strictHandler) UploadAvatar(ctx echo.Context, params UploadAvatarParams) error {
	var request UploadAvatarRequestObject

	request.Params = params

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UploadAvatar(ctx.Request().Context(), request.(UploadAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadAvatar")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UploadAvatarResponseObject); ok {
		return validResponse.VisitUploadAvatarResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteAvatarById operation middleware
func (sh *strictHandler) DeleteAvatarById(ctx echo.Context, avatarId AvatarIdPath, params DeleteAvatarByIdParams) error {
	var request DeleteAvatarByIdRequestObject

	request.AvatarId = avatarId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAvatarById(ctx.Request().Context(), request.(DeleteAvatarByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAvatarById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteAvatarByIdResponseObject); ok {
		return validResponse.VisitDeleteAvatarByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAvatarById operation middleware
func (sh *strictHandler) GetAvatarById(ctx echo.Context, avatarId AvatarIdPath, params GetAvatarByIdParams) error {
	var request GetAvatarByIdRequestObject

	request.AvatarId = avatarId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAvatarById(ctx.Request().Context(), request.(GetAvatarByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAvatarById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAvatarByIdResponseObject); ok {
		return validResponse.VisitGetAvatarByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAvatarMetadata operation middleware
func (sh *strictHandler) GetAvatarMetadata(ctx echo.Context, avatarId AvatarIdPath) error {
	var request GetAvatarMetadataRequestObject

	request.AvatarId = avatarId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAvatarMetadata(ctx.Request().Context(), request.(GetAvatarMetadataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAvatarMetadata")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAvatarMetadataResponseObject); ok {
		return validResponse.VisitGetAvatarMetadataResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteUserAvatar operation middleware
func (sh *strictHandler) DeleteUserAvatar(ctx echo.Context, userId UserIdPath, params DeleteUserAvatarParams) error {
	var request DeleteUserAvatarRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUserAvatar(ctx.Request().Context(), request.(DeleteUserAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUserAvatar")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteUserAvatarResponseObject); ok {
		return validResponse.VisitDeleteUserAvatarResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUserAvatar operation middleware
func (sh *strictHandler) GetUserAvatar(ctx echo.Context, userId UserIdPath, params GetUserAvatarParams) error {
	var request GetUserAvatarRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserAvatar(ctx.Request().Context(), request.(GetUserAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserAvatar")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserAvatarResponseObject); ok {
		return validResponse.VisitGetUserAvatarResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListUserAvatars operation middleware
func (sh *strictHandler) ListUserAvatars(ctx echo.Context, userId UserIdPath, params ListUserAvatarsParams) error {
	var request ListUserAvatarsRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListUserAvatars(ctx.Request().Context(), request.(ListUserAvatarsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUserAvatars")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListUserAvatarsResponseObject); ok {
		return validResponse.VisitListUserAvatarsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(ctx echo.Context) error {
	var request HealthCheckRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx.Request().Context(), request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		return validResponse.VisitHealthCheckResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetGalleryPage operation middleware
func (sh *strictHandler) GetGalleryPage(ctx echo.Context, userId UserIdPath) error {
	var request GetGalleryPageRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetGalleryPage(ctx.Request().Context(), request.(GetGalleryPageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGalleryPage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetGalleryPageResponseObject); ok {
		return validResponse.VisitGetGalleryPageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUploadPage operation middleware
func (sh *strictHandler) GetUploadPage(ctx echo.Context) error {
	var request GetUploadPageRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUploadPage(ctx.Request().Context(), request.(GetUploadPageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUploadPage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUploadPageResponseObject); ok {
		return validResponse.VisitGetUploadPageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUploadForm operation middleware
func (sh *strictHandler) PostUploadForm(ctx echo.Context) error {
	var request PostUploadFormRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUploadForm(ctx.Request().Context(), request.(PostUploadFormRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUploadForm")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUploadFormResponseObject); ok {
		return validResponse.VisitPostUploadFormResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FvrbhvHFX6VwbY/bGApLkXacQX0hy+xo9YJ1MhG2iaGseKOyLXJ3c3u0LZiEJDIJHbgwKrTFC3QNEkv",
	"D0DJYkRLIvUKM6/QJynOmb1zSFG0ckFbwDDI5c7MuZ/vnDl6rFXdpuc61GGBtvRY80zfbFJGffx2+YHJ",
	"TH/ZWjFZHb5bNKj6tsds19GWtNu3l68R3uO7vCc6vCc2+QEfaLpmw48eLNE1x2xSbUkzcaO7tqXpmk8/",
	"bNk+tbQl5reorgXVOm2asP266zdNpi1prRa+yTY8WBww33ZqWruta7cD6i9bb1HTov44QfwvfI/3+VB0",
	"+EB8zAf8ACkbiU3Cj/mIH4rP+T4fhQT3+aHY1gnfFc/kr3wotsVz8Rnv85d8RPiIH/O+2OQ98SkfiOcR",
	"Z3V5eszbbwtAVWH52lTeJvGiFu0cnKgF3wroiWLPk9aGlwPPdQKKVnDFtN6lH7ZowOBb1XUYdfCj6XkN",
	"u2oCzcV7ARD+OLXtz326ri1pPysmFlaUvwbFN33f9eVROcb/xvv8ABgVm/BJdPhQPOOvCN/nPX4sNvlI",
	"bGltXVt2GPUdsyF3Opku+shseg2KH+WSeAsSUP8B9Yl83tZfm4cv+FB0RQc5GKJVbRM+Ek/5gO+AJonY",
	"QsPa5QOxxXtw5Dsuu+62HGs+TqSfEsdlZB13OQMmvuV9sSW6YlNsET7kffivx19Ju4QDbjtmi9Vd3/6I",
	"npJsizLTbgRp3yHSq4gdkNhQ9Zi/zFFnwNvXooO8wf8dviu6vC86hA/4IR8gszkT7POhNMCXGCfA70b8",
	"gCSe346JSsXNtykzLZMhnZ7vetRntvSoqk9NRq27JsuEPctktMDsJh2Pfbpm2U3qBLbrBCfxfS15s61r",
	"63aD3pXRIKWEMCIv3PNqqsNsa4Z4rGtNu0nvyqfpve2mWaPFex5V7u35bpUGge3U7gbMZC3khzqtprb0",
	"vuZRx4L30q9pOiapBmVoFOum3aCWdkexdWB/lCWlZCxWDMPQE1Zsh12sJGTZDqM1il7P6q3mmiMN87Fm",
	"M9o8UdK3oiXLzrqLe8hdTd83N+B7y7NOreiW13BNSyEb+YMUiPx8kjyi6K/MP0lCeF9D9Sa5IrGZtI5D",
	"+epp882wmJDgrt2jVQYkSFe4jeS+G2aVs3GIGW1UYWNzWFbLbyikOL+EYb+YtoxEVUK8GpneasxMVn40",
	"yoJjBDZMRp3qxl1pzONWPy4e934cee/oJ3AVrlbRfC0Tr7Lk1qldqzM1QQ9tSyKi/E+5o+V7erSXioQY",
	"G2RPj9OPQlyTBJk7PC+e5MzrdoPect2bpl+jE86Pz0giJqwizHVJA9YpQ6356K4ivFUuXXjj4izxTclA",
	"alsVL29Rs8Hqk2wuVzhkflvz3fsSoU8Ln3mzhixnMnPNlCHilEuD8qkXtRVMT3AIi9b8MOBa7kNnZtfQ",
	"03JSCTmbQ8YkOaZzrWQYj0qGoc0cpfKEySAO747TAwKg1ZZvs41VkJokQpYql1tnVKqQsLDq8z3eEy8Q",
	"hm0TvpvHWAeAOvfkikwxxl/pJMTXO6KLNdtAfEL4Lj/kPSTnUHwuPgWkvZnAWN6bpYSLUrhn/5puSPRo",
	"h5oBhGtWMW6FC2+4Xn3FdyFfklvUbGrjWPMrEImsWxLQH7OFDItN0eX7UD3rRHwCTCIGHfIBFqgjvoPP",
	"dvhIdOAtwgcEn+yjAJ/Ak3QZDthULXve568WCP9GqZfP0+R8x3sIisXHeOoIHvMeKFg8B5L2+IAPQyp0",
	"PE1swf5EPAnrZ8TWIyRnCLyAMo9BQaKDm27yI/GM8CPcuwv4W5LcBYZEB8hJMYW/AkSfYGyiO9HcFgj/",
	"ExI3yO2Yr2rIvze/JFk1AXXfyeoAxLAXbQDUDfAgqZvvpL54vxDaMPDxlB+I7sIHDliVzRp5gwmrtlXq",
	"P7CrlFxeWdZ07QH1A2k5pQVjwQCDcj3qmJ6tLWnlBWOhDNjYZHV0zKLp2cUHpaJE8zIQu7JOz5nhn8c0",
	"q6Z/mhT/haI6BBGNIjsV27BZ5MCrZR1k1gcJo7CGWL73UbJ8l6y4Aav5dPU3N6UVRjaT2jAyfIImMuAv",
	"wdB4DwwHQ8SONHBQEq5DFj4LyX9F+LHo8h1QNgg/pg3f3BHPwHBSUaUntmB7PFua6Si0XT6S3hURc4Rk",
	"DFD3z8UmOReGYZ2UDeNR2TDOS0VD7MbCd9mCwhVxr1Q06i3prr2vzlXJK8VMs6t9R0ZxGrArrrWRK7ib",
	"rQazPdNnRQAChajqTOrkbFIB81PYSKRflWWIbXLuVytv3tDJyjs3dPIeXVs5j7ru8QMU4pHo8iNSMt6+",
	"oqXgyJrtmP6GdlKyRIIU2aid71vle1OLRul0vYd0paEtGouVglEqGKVbhrGE/36vycpCu3DBoJcqhlGg",
	"i79YK1RKVqVgvlG6WKhULl68cKECZaWRQPilbFWBiTjvncUZt4xrCvxUKC2WZ+95KMstVQvkD6lAKLpi",
	"C9PrU3AAgm22AfatIEqEwR1dehdTyBAdcQSRXmZxiIZD8M9cqhJdoLxiGPP2h1Zbnuf6jFpEWlSwRO55",
	"tKYTz6np5CFd81JdomXngdmwLYLBNbTAM2gWTepIRkkMxAhf0HdkN68irVJ1Xmy9xXxTq1Iqz9f9Gyse",
	"klohKhBmFsN4+aISSRwojlEmu+KZeBpllT2AamBRGGqPpKgkWIHEsAmsXpAWMV0+2Q4vItNWswnRJJPO",
	"9rGjqriGYGYNwmzYgQi0O7BF3iUfxzcTbWl5DcpUofGL9CWBZPRIbPOXYBmQwLqYKw6TLIrtauzvDtBb",
	"XvAvyblQLD1MaLuYpHZDucmTIS6dlz6XT2OnTmEZkiAFRiY6AnoGfJ+sllU56xpSIqV2ZWPZOnXeytwa",
	"tfV58lwmwlcU+pgSviLGxQvZp57PGY3yvDHrd26LVE2HuE5jI1Qr2XBbPnEfOiQCaknUuu76a7ZlUecs",
	"YtU36HzPsEzoJSYg4bR4guhvBCgp5S6S3crJMorvKM7Eg/+Z95hZPFjXahS1kTXZG5Sdpb3mhPqPqNDk",
	"fUU8m4CWolLzwxZF/BMWjGHxnejZoutmqwFgxPXtmu2YDbCNsPOQlPohyARnjV5TdSBmoT2dtk5Fe5hS",
	"09RHhIa9fg/BD6ZlBXXjnp3HBamLgwx6nQVOyrVAwZxLkexTrh33wBeyXBGbYeGTqYImils2JFAqV81q",
	"nRauug7z3UaWnqQH1DQfFcwa/eWlixVVJ6ita2/eMmuTVn+gmaW1xWrZqnygqZj6cQLCN3H1PykkkHN8",
	"5/TiPT8HFig2U3d300NOfMv3emHnZOeY/7Y9R6jKbL9S1OxjEfknYxdjHQbxybT8EXOeUTsUV0HxcVht",
	"tUMzyKJAFTICuPJaFf1/Py76H4Yx2C47EF1sSb0aD2FTxncicwW9Z8BOTjpRM3NKy5Ng17uTb+n2Q9/O",
	"0hU257DjtYtd3s+iYg47uTP3T/XJzdNdfC7HYmZuncqer+jiRofiSdiNe66qWm5QdnaO+aMgt/9Drh8O",
	"cpFzY3cLajc6xJmtEcmaJu+d/4FA208Wm51hnDsxJwcTUdhNO0i5ffB9+H3DbtpM7fiLBvba7CZ4ZMmA",
	"b7YTflPdwKsPcNfXAzrhhPSWhmLL10WN2WuBeOZppuGnPKocn36Sokv7wKKhmrwKJZB+Ufkec5nZyLxW",
	"Vg46KG4RciHj72FvDm9KZ7s6Fds/EsKYj1a1m9VxoiPlTnnghdtiso7anHuy+S+6/BhgZAgrkos8nayW",
	"C/HlHY5QAn7AJmbqrk5OveZu68ayuJw4uVqn1fvaXKadvunJzKckEynpiagLqQsc935+ACX9ZnnsTTlv",
	"kn6ntJh7qT2+aCZknBm8UdtvCmYNCN8F4CWTlBwqHgBmkj14krqR6YnnokPEU/zYAX1KGy2fvWgvziza",
	"ygTRRh3Squs4tAq0EGY3qdti6Xs3mvhM9Cie1Tk7gX8dDjykZoTFFjb/wfkOACHAlyP0x2E4ooCN9iGO",
	"uaR8SDwby66J18mCJ1HYCEu4kez9R/4HOs1OkCfeLjkJ3f0hXSvWzEaD+htJUp3W0rghX14x8R5p/lx6",
	"cl5i9BEr1lmzcQLeyWvirVtv3yygMMOAI8d8tgh/KeswbHiOQZIzjutZ/f0xORlvZE4fo9+jaymVyeHe",
	"aXqSF7yhmn5oSccd5FH0dxmpCaax7HXK9dP6OFJKejzikhULpCQpl+uu39S+h3GJE4uTU8wDv8bEw1kp",
	"mH/L+3xfdHFYriPvA/LaOAdWcD6pg8KpvUF0F453mynPE89BCmVjUQEuvs0vHaI9pA0Eav60Hw8yk2WZ",
	"fpbS9uJhg+mOnPqLppy5fp2bteuNiyQee9jHtgbfKcTjbN1xl8aBSv9BFENzIvkrwqMeRoch3iTDg1S3",
	"BkstvG3KjgDGMyZ1xrylYrHhVs1G3Q3Y0iXjkqG4xVrxXauFSTSzNFgqQu21UHO9uifn0hbCRL9QdZsY",
	"yUOOHo/nxPRI5kAxzJia6IunugbjN9P5iJnURlFdp7jZyp8OKSAbOnr8SF6+xwLs8/0pE27JsRIyKw6d",
	"vxcd7pwql6aB77lhQHhMiAIUh3yBFosTAx2E+R9DshRb5NzqymVSTHbsh/2UVyT8O7Y9fDTgQ/7yfHIS",
	"mHn7Tvs/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
